### ISSUE TITLE
 Unable to write or read using webclient or postman

### ISSUE THREAD

**Issue by amgtel** [eclipse/kuksa.val#10]
I am trying to read from w3c using webclient and postman and I can authorize but when I try to read, write,etc a value:

Example with postman
GET http://localhost:8090/vss/api/v1/
{
"action": "get",
"requestId": "1234",
"path": "Vehicle.OBD.EngineSpeed"
}

It says:

>     ERROR: HTML status = 404
>     {
>     "action": "get",
>     "error": {
>     "message": "I can not find Requested resource do not exist in my db",
>     "number": 404,
>     "reason": "Path not found"
>     },
>     "requestId": "1079400840",
>     "timestamp": 1587719333
>     }

The vss_rel_2.0.json is correct and testclient works.

This problem was an issue closed here [https://github.com/eclipse/kuksa.invehicle/pull/113](url)
but it was not resolve.

**Comment by SebastianSchildt** [comment]
Hi, I am not "fluent" in the REST interface, and need some time to replciate, however, just in case the 404 is misleading: Did you authorize first? The REST API also needs a valid  JWT token before it works. 

testclient uses websocket, so it could be that it works, while you did something else with POSTMAN.  Did you also try with the REST test thingy https://github.com/eclipse/kuksa.val/tree/master/test/web-client  ? (and if the testclient works you might look what it does using Wireshark, and compare it what you are doing with postman)

maybe @BojanKV is still alive and remembers something

**Comment by amglcc** [comment]
Hi, yes, I have not problems with testclient using websocket, I can authorize, read and write with no problem.

Using  web-client and postman (I use postman to do different proofs configuring w3c-visserver with a different IP to access to it from external)

With POSTMAN and web-client I can only authorize.

Good idea, I am going to use wireshark to compare.

**Comment by SebastianSchildt** [comment]
For future reference, `GET`  needs to be on e.g. signals/Vehicle.Speed  with the experimental REST support,
