### ISSUE TITLE
System health metrics

### ISSUE THREAD

**Issue by SebastianSchildt** [eclipse/kuksa.val#100]
Add a VSS sub-model to model performance metrics such as CPU laod, memory pressure of the host device and write a feeder

May be good issue for learning

**Comment by adityaofficial10** [comment]
Hey @SebastianSchildt !
Can I work on this issue and can you help me getting started with this?
That will be a great help.

**Comment by SebastianSchildt** [comment]
Hi @adityaofficial10    
Of course you can try. The easiest way building feeders ist using our python websocket code here https://github.com/eclipse/kuksa.val/tree/master/clients/common   
to get a feeling how to use it look into the testclient code https://github.com/eclipse/kuksa.val/tree/master/clients/vss-testclient  or the GPS feeder https://github.com/eclipse/kuksa.val/tree/master/clients/feeder/gps2val

You will probably also need to extend the data model, you can check the docs here https://github.com/eclipse/kuksa.val/blob/master/doc/liveUpdateVSSTree.md

Regarding the systemstat feeder there is also some experimental, not complete code in RUST flying around using the (undocumented, more primitive) REST interface (--insecure mode only) here: https://github.com/boschresearch/kuksa.val/tree/feature/systemstat-feeder-test/clients/feeder/system-monitor-feeder   ,  but feel free to either pick it up or ignore it and start from scratch. This was more like an experiment. Might still serve as an example how to extend the data model: https://github.com/boschresearch/kuksa.val/blob/feature/systemstat-feeder-test/clients/feeder/system-monitor-feeder/model/systemstat.yaml  . The YAML need to be translated to json using the tooling here https://github.com/GENIVI/vss-tools , but i think this is als mentioned in the documentation linked above

**Comment by erikbosch** [comment]
We are about to archive this repo soon. If you consider this issue as important please file a new issue at one of the new Kuksa repos at https://github.com/eclipse-kuksa
