### ISSUE TITLE
segmentation fault again using nodered secure examples

### ISSUE THREAD

**Issue by wenwenchenbosch** [eclipse/kuksa.val#105]
Error logs:

```
INFO: kuksa-vss = object
ERROR: Authenticator::validate: token verification failed: token expired Exception occurred while authentication. Token is not valid!
VERBOSE: Receive action: getMetaData
VERBOSE: VssCommandProcessor::processQuery: get MetaData query  for * with request id 1236
VERBOSE: VssDatabase::getMetaData: VSS specific path =$['Vehicle']
VERBOSE: Receive action: get
terminate called after throwing an instance of 'jsoncons::jsonschema::schema_error'
  what():  VSS get malformed: #/requestId: Expected string, found uint64

fish: “./kuksa-val-server” terminated by signal SIGABRT (Abort)
````

**Comment by SebastianSchildt** [comment]
SIGABRT!=SIGSEV. Root cause seems that JSON Scheam validation fails. But crash seems harsh. Can you fix it? :)   (For letting  example run, put the request-id in quotes "", I assume from the error message you don't

**Comment by SebastianSchildt** [comment]
guessing, maybe a try/catch required here: https://github.com/eclipse/kuksa.val/blob/83f8d9b19733092f579656d25819a2e7f6cb1a59/src/VssCommandGet.cpp#L28

**Comment by wenwenchenbosch** [comment]
> SIGABRT!=SIGSEV. Root cause seems that JSON Scheam validation fails. But crash seems harsh. Can you fix it? :) (For letting example run, put the request-id in quotes "", I assume from the error message you don't

oh I always read half words...
I fixed it already. You were too fast. pls review.

However, I recognize that, only validation of get request is done, not for other request types, any plan to also validate other requests?

**Comment by SebastianSchildt** [comment]
> However, I recognize that, only validation of get request is done, not for other request types, any plan to also validate other requests?

Of course, as discussed here https://github.com/eclipse/kuksa.val/pull/86
However a little pressed for time, was working on set path, but currently 3 weeks overdue
