### ISSUE TITLE
Incorrect information display regarding insecure mode.

### ISSUE THREAD

**Issue by nayakned** [eclipse/kuksa.val#114]
By default kuksa.val server is supposed to start in secure mode, i.e., SSL enabled.
While the server does start in secure mode, the output on the console is contradicting.

This line in the console output must be removed for secure mode or default execution:
INFO: Attention! Insecure connection are allowed! Do not use this in production!

**Comment by wenwenchenbosch** [comment]
Just see that our default config is insecure, see: https://github.com/eclipse/kuksa.val/blob/aeaa9adb28ce672ec2adde8cf553622b281d04e7/test/unit-test/config.ini#L2
It is not safe, I will remove it
