### ISSUE TITLE
run and test kuksa.val clients automatically in the CI pipline

### ISSUE THREAD

**Issue by wenwenchenbosch** [eclipse/kuksa.val#120]
https://github.com/eclipse/kuksa.val/issues/119 can be used to test clients logic.

Test Scenarios could be:
- For MQTT clients: Replay a recorded data to test if a MQTT client can receive data in a correct order and if all configured topics are published.

**Comment by erikbosch** [comment]
I am closing this one.I know we could improve integration tests but the referenced solutions here are a bit outdated.
