### ISSUE TITLE
Links to VISS 2.0 standard broken in readme

### ISSUE THREAD

**Issue by mwagner1886** [eclipse/kuksa.val#127]
There are two links pointing to the VISS 2.0 standard in the readme. Both are broken.

Broken links:
https://raw.githack.com/w3c/automotive/gh-pages/spec/Gen2_Core.html
https://raw.githack.com/w3c/automotive/gh-pages/spec/Gen2_Transport.html

**Comment by SebastianSchildt** [comment]
fixeed in #126
