### ISSUE TITLE
add grpc interface to kuksa.val

### ISSUE THREAD

**Issue by wenwenchenbosch** [eclipse/kuksa.val#131]
After https://github.com/GENIVI/vss-tools/pull/42 is merged, there would be a proto file availiable for vss model. It would be nice to implement a grpc interface for kuksa.val.

**Comment by SebastianSchildt** [comment]
Questions

- which abstraction (simple or on datapoint level? Is it dynamic)
- security: External components "trusted", or need to use JWT to set up security context
- Interface scope "larger" than Websocket?

**Comment by SebastianSchildt** [comment]
I am not necessarily convinced it is a good basis for our interface, but for going "deep" into a specific tree, attached is the output of the current vss-tools protobuf converter 

[vss_rel_2.1-develop.pb.zip](https://github.com/eclipse/kuksa.val/files/6287246/vss_rel_2.1-develop.pb.zip)
