### ISSUE TITLE
s3 upload does not work any more for parent path after changing getValue format

### ISSUE THREAD

**Issue by wenwenchenbosch** [eclipse/kuksa.val#132]
this config does not work any more:
https://github.com/eclipse/kuksa.val/blob/fa4ebe4111bb43cebfacf35d6eefbee2bd6ebe98/clients/s3/config.ini#L14

workaround is change to 
```
path = Vehicle.Speed, Vehicle.Cabin.Infotainment.Navigation.DestinationSet.Longitude, Vehicle.Cabin.Infotainment.Navigation.DestinationSet.Latitude
```

currently, only path without children is supported

**Comment by SebastianSchildt** [comment]
Closing, as we just dropped that feature. Just explicit paths supported in new S3 uploader.
