### ISSUE TITLE
GPSD feeder can not be killed with strg-c

### ISSUE THREAD

**Issue by SebastianSchildt** [eclipse/kuksa.val#154]
When starting GPSD feeder in docker, it can not be stopped via Strg-C

**Comment by wenwenchenbosch** [comment]
actually the pull request for the dockerfile https://github.com/eclipse/kuksa.val/pull/147 is still open

**Comment by wenwenchenbosch** [comment]
ok I find out the problem. gspd blocks, if no connection via udp there. I will have look at it and fix it direkt in the pull request above

**Comment by wenwenchenbosch** [comment]
I reported a bug to gps library: see https://gitlab.com/gpsd/gpsd/-/issues/131
