### ISSUE TITLE
Switch getMetadata to "/" format

### ISSUE THREAD

**Issue by SebastianSchildt** [eclipse/kuksa.val#157]
getMetadate should support "/" VSSPaths

**Comment by SebastianSchildt** [comment]
There also is the question how to implement it, in VISS2 it is mangled with the overcomplex "filter" semantic https://raw.githack.com/w3c/automotive/gh-pages/spec/VISSv2_Transport.html#wss-service-discovery-read which we will definitely not support on kuksa.val  level.

However, it might make sense to use the get call and only parse for this filter specifically. It is ugly, but could be hidden by the viss client library, and would be standard compliant

**Comment by wenwenchenbosch** [comment]
I will close this issue and opend a new issue for the `filter` issues: https://github.com/eclipse/kuksa.val/issues/188
