### ISSUE TITLE
set multiple values possible?

### ISSUE THREAD

**Issue by wenwenchenbosch** [eclipse/kuksa.val#167]
Is it possible to set multiple values at once? If yes, how?
If no, why in the implementation vector is used:
https://github.com/eclipse/kuksa.val/blob/0303155cd2f3ec3dec92a0bc827d1711f9ea8237/src/VssCommandSet.cpp#L59

Another related question: why is the limit check implemented for https://github.com/eclipse/kuksa.val/issues/46 not a preliminary check and happend inside the `setSignal` function in database and after the comment:
https://github.com/eclipse/kuksa.val/blob/0303155cd2f3ec3dec92a0bc827d1711f9ea8237/src/VssCommandSet.cpp#L80-L83

**Comment by SebastianSchildt** [comment]
As agreed, we removed the support when changing to VSSPath, it will be reintroduced, when we change the "value" syntax to the "dp" syntax (in VISS1 multiple sets haven' been defined in Spec).

That the limit check it not a preliminary, can be considered a bug i guess :(    But maybe it does not need to be fixed at the same time as introducing enum checks? As to not mix issues

**Comment by SebastianSchildt** [comment]
see also #158

**Comment by SebastianSchildt** [comment]
Multiple Sets not supported in VISS; will be in GRPC
