### ISSUE TITLE
redudant token entries are not checked

### ISSUE THREAD

**Issue by wenwenchenbosch** [eclipse/kuksa.val#168]
the following two token json files are valid but the behaviors are different:

```
…ata/tools/kuksa.val/kuksa_certificates/jwt ((9288e9f5…)) [I]  cat some-read-write.json
{
  "sub": "kuksa.val",
  "iss": "Eclipse KUKSA Dev",
  "admin": true,
  "iat": 1516239022,
  "exp": 1767225599,
  "kuksa-vss":  {
     "Vehicle.OBD.*": "r",
     "Vehicle.OBD.*": "rw"
  }
}
```
```
…ata/tools/kuksa.val/kuksa_certificates/jwt ((9288e9f5…)) [I]  cat some-read-write2.json
{
  "sub": "kuksa.val",
  "iss": "Eclipse KUKSA Dev",
  "admin": true,
  "iat": 1516239022,
  "exp": 1767225599,
  "kuksa-vss":  {
     "Vehicle.OBD.*": "rw",
     "Vehicle.OBD.*": "r"
  }
}
```

Using the first token, I can set value of `Vehicle.OBD.Speed`, with the second token, I can't do it

**Comment by wenwenchenbosch** [comment]
not easy to fix, after decode using jwt, only the first item is there:
https://github.com/eclipse/kuksa.val/blob/9288e9f57105efc321ec72ba912ffdb91f807095/src/Authenticator.cpp#L65

Maybe error message in the createToken script is necessary?

**Comment by SebastianSchildt** [comment]
this seems to be JSON related. Maybe it is correct JSON semantic, when you overwrite an existing key? Because JSON files used to be "digestible" by Javascript interpreters, so it is like reassigned a variable.

I agree, in our usecase it might be confusing if you have really a LOT of rules and add one.

**Comment by SebastianSchildt** [comment]
Found this: https://stackoverflow.com/questions/21832701/does-json-syntax-allow-duplicate-keys-in-an-object   
(consensus seems to be  "it is not illegal, better don't do that" )

Undefined behaviour territory

**Comment by SebastianSchildt** [comment]
Closing deprecated val-server related ticket
