### ISSUE TITLE
is all function in VssDataBase threadsafe?

### ISSUE THREAD

**Issue by wenwenchenbosch** [eclipse/kuksa.val#180]
some query is not protected by mutex:

https://github.com/eclipse/kuksa.val/blob/761420934fd7cf3497032565a21c937f35c7c0d3/src/VssDatabase.cpp#L111

**Comment by SebastianSchildt** [comment]
Probably not :) Should consider this a bug, secure every access to the jsoncons main tree.

I would assume multiple reads are not a problem, so for performance in the longterm probably write should lock the whole tree for everyone, and read should only lock it for write

**Comment by SebastianSchildt** [comment]
val-server seems stable and is in maintenace mode anyway. Closing
