### ISSUE TITLE
Reactivate stresstest and integrate the stresstest to CI pipline

### ISSUE THREAD

**Issue by callalilychen** [eclipse/kuksa.val#197]
- test the stresstest under https://github.com/eclipse/kuksa.val/tree/master/test/stresstest.
- Use python sdk in stresstest
- integrate stresstest to CI pipline (jenkinsfile)

**Comment by SebastianSchildt** [comment]
Related to #393

**Comment by SebastianSchildt** [comment]
Closing this, we meanwhile have basic  integration tests for databroker in CI for a long time

stresstest itself may be replaced by a "better"/real performance test, but I guess that would be another discussion, so closing here
