### ISSUE TITLE
TLS client authentication support for mqtt publish in kuksa.val

### ISSUE THREAD

**Issue by wenwenchenbosch** [eclipse/kuksa.val#213]
[`mosquitto_tls_set`](https://mosquitto.org/api/files/mosquitto-h.html#mosquitto_tls_set) can be used for building a secure channel hier:

https://github.com/eclipse/kuksa.val/blob/d81ff3d0d85a2d7674a4898a6e9199a06cd75e0b/src/MQTTPublisher.cpp#L51

**Comment by Vinait** [comment]
Hi, Will the Kuksa-val-server supports MQTT protocol or only the Web-socker only ? Kindly help

**Comment by lukasmittag** [comment]
Hey, KUKSA.val server will get no new features. For the KUKSA.val databroker there is a grpc API and you could use something like https://github.com/awakesecurity/grpc-mqtt .

**Comment by Vinait** [comment]
Sure. Will check the Data Broker repository shared. 
But, still wanted to clarify the Kuksa-val-server existing features, will the current delivery supports MQTT communication ?

**Comment by lukasmittag** [comment]
Ah now I see, so to get mqtt publisher of kuksa-val-server up and running you do the following:
``` 
mosquitto_sub -t \#
```
start the kuksa-val-server (I used the docker container if you want to build it use the KUKSAVAL_OPTARGS as cli args):
```
docker run -it --rm --net=host -v $HOME/kuksaval.config:/config  -p 127.0.0.1:8090:8090 -e LOG_LEVEL=ALL -e KUKSAVAL_OPTARGS="--mqtt.publish Vehicle.* --insecure" ghcr.io/eclipse/kuksa.val/kuksa-val:master
```
then start kuksa-client:
```
docker run -it --rm --net=host ghcr.io/eclipse/kuksa.val/kuksa-client:master --protocol ws --insecure
```
and do this:
```
Welcome to Kuksa Client version 0.3.1.post70+git.3308d930.dirty

                  `-:+o/shhhs+:`                  
                ./oo/+o/``.-:ohhs-                
              `/o+-  /o/  `..  :yho`              
              +o/    /o/  oho    ohy`             
             :o+     /o/`+hh.     sh+             
             +o:     /oo+o+`      /hy             
             +o:     /o+/oo-      +hs             
             .oo`    oho `oo-    .hh:             
              :oo.   oho  -+:   -hh/              
               .+o+-`oho     `:shy-               
                 ./o/ohy//+oyhho-                 
                    `-/+oo+/:.             

Default tokens directory: /home/imu6fe/kuksa.val/kuksa_certificates/jwt

connect to ws://127.0.0.1:8090
Websocket connected.
Test Client> authorize kuksa_certificates/jwt/all-read-write.json.token 
{
  "TTL": 1767225599,
  "action": "authorize",
  "requestId": "b9b51624-cacf-4ac1-9e55-64954691d2f3",
  "ts": "2023-07-12T07:28:22.1689146902Z"
}

Test Client> setValue Vehicle.Speed 100
{
  "action": "set",
  "requestId": "2764f5fa-5a66-4762-8807-fb6845231fbb",
  "ts": "2023-07-12T07:28:24.1689146904Z"
}

Test Client> setValue Vehicle.Speed 120
{
  "action": "set",
  "requestId": "324a2b5f-b35c-43c0-bc63-a0cc7b7f30d8",
  "ts": "2023-07-12T07:28:27.1689146907Z"
}

Test Client> 
```
and you will see in the terminal with the mosquitto subscriber:
```
100.0
120.0
```
So yeah itsupports mqtt protocol.

**Comment by Vinait** [comment]
Sure
When I tried using the shared dockers,  and tried to set Vehicle Speed using Kuksa-Client.


At Server, gets following error
ERROR: MQTT Connection Error: Connection refused
ERROR: MQTT Connection Error: Connection refused
ERROR: MQTT Connection Error: Connection refused
ERROR: Cannot send to connection, server not initialized!
VERBOSE: SubscriptionHandler::publishForVSSPath: set value 100.0 for path Vehicle.Speed


At Mosquitto,

 mosquitto_sub -t \#
Error: Connection refused

**Comment by lukasmittag** [comment]
can you please provide the commands you used? Where is your mosquitto running (address, port)?

**Comment by Vinait** [comment]
Just used below 3 commands
-------------------------------
docker run -it --rm --net=host -v $HOME/kuksaval.config:/config  -p 127.0.0.1:8090:8090 -e LOG_LEVEL=ALL -e KUKSAVAL_OPTARGS="--mqtt.publish Vehicle.* --insecure" ghcr.io/eclipse/kuksa.val/kuksa-val:master

docker run -it --rm --net=host ghcr.io/eclipse/kuksa.val/kuksa-client:master --protocol ws --insecure

mosquitto_sub -t \#

**Comment by Vinait** [comment]
Issues with details, tried with local setup

./kuksa-val-server  --vss ./vss_release_4.0.json  --log-level ALL --insecure  --mqtt.address localhost  --mqtt.port 8090 --mqtt.keepalive 60 --mqtt.publish Vehicle.* 

Kuksa-Client:
      kuksa-client --protocol ws --insecure

mosquitto_sub -h localhost -t Vehicle.* -d

    Client (null) sending CONNECT
    Client (null) received CONNACK (0)
    Client (null) sending SUBSCRIBE (Mid: 1, Topic: vss/Vehicle/Speed, QoS: 0, Options: 0x00)
    Client (null) received SUBACK
    Subscribed (mid: 1): 0
   Client (null) sending PINGREQ
   Client (null) received PINGRESP
   Client (null) sending PINGREQ
   Client (null) received PINGRESP


Error Shown at Kuksa-val-server:
-----------------------------------
kuksa.val server
Commit aa52dd3-dirty from 2023-06-21T16:42:07+02:00
Read configs from config.ini
Update vss path to /home/vinait/kuksa.val/KUKSA_DEPLOY/kukval-server/./vss_release_4.0.json
Update cert-path to /home/vinait/kuksa.val/KUKSA_DEPLOY/kukval-server/.
Log START
VERBOSE: Try reading JWT pub key from /home/vinait/kuksa.val/KUKSA_DEPLOY/kukval-server/./jwt.key.pub
VERBOSE: SubscribeThread: Started Subscription Thread!
VERBOSE: VssDatabase::VssDatabase : VSS tree initialized using JSON file = /home/vinait/kuksa.val/KUKSA_DEPLOY/kukval-server/./vss_release_4.0.json
INFO: Setting default for Vehicle/Cabin/DoorCount to 4
INFO: Setting default for Vehicle/Cabin/SeatPosCount to [2,3]
INFO: Setting default for Vehicle/Cabin/SeatRowCount to 2
INFO: Setting default for Vehicle/Chassis/AxleCount to 2
INFO: Setting default for Vehicle/Chassis/Wheelbase to 0
INFO: Setting default for Vehicle/CurbWeight to 0
INFO: Setting default for Vehicle/GrossWeight to 0
INFO: Setting default for Vehicle/Height to 0
INFO: Setting default for Vehicle/Length to 0
INFO: Setting default for Vehicle/MaxTowBallWeight to 0
INFO: Setting default for Vehicle/MaxTowWeight to 0
INFO: Setting default for Vehicle/Powertrain/CombustionEngine/AspirationType to UNKNOWN
INFO: Setting default for Vehicle/Powertrain/CombustionEngine/Configuration to UNKNOWN
INFO: Setting default for Vehicle/Powertrain/CombustionEngine/MaxPower to 0
INFO: Setting default for Vehicle/Powertrain/CombustionEngine/MaxTorque to 0
INFO: Setting default for Vehicle/Powertrain/ElectricMotor/MaxPower to 0
INFO: Setting default for Vehicle/Powertrain/ElectricMotor/MaxRegenPower to 0
INFO: Setting default for Vehicle/Powertrain/ElectricMotor/MaxRegenTorque to 0
INFO: Setting default for Vehicle/Powertrain/ElectricMotor/MaxTorque to 0
INFO: Setting default for Vehicle/Powertrain/FuelSystem/HybridType to UNKNOWN
INFO: Setting default for Vehicle/Powertrain/Transmission/DriveType to UNKNOWN
INFO: Setting default for Vehicle/Powertrain/Transmission/GearCount to 0
INFO: Setting default for Vehicle/Powertrain/Transmission/Type to UNKNOWN
INFO: Setting default for Vehicle/StartTime to 0000-01-01T00:00Z
INFO: Setting default for Vehicle/VersionVSS/Major to 4
INFO: Setting default for Vehicle/VersionVSS/Minor to 0
INFO: Setting default for Vehicle/VersionVSS/Patch to 0
INFO: Setting default for Vehicle/Width to 0
VERBOSE: MQTTPublisher::addPublishPath: Vehicle.*
INFO: Initializing Boost.Beast web-socket and http server on 127.0.0.1:8090
INFO: Attention! Insecure connection is also allowed now! Do not use this in production!
INFO: Starting Boost.Beast web-socket server
INFO: Kuksa viss gRPC server Version 1.0.0
INFO: gRPC Server listening on 0.0.0.0:50051
VERBOSE: Receive action: authorize
VERBOSE: VssCommandProcessor::processQuery: authorize query with token = eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJrdWtzYS52YWwiLCJpc3MiOiJFY2xpcHNlIEtVS1NBIERldiIsImFkbWluIjp0cnVlLCJpYXQiOjE1MTYyMzkwMjIsImV4cCI6MTc2NzIyNTU5OSwia3Vrc2EtdnNzIjp7IioiOiJydyJ9fQ.QQcVR0RuRJIoasPXYsMGZhdvhLjUalk4GcRaxhh3-0_j3CtVSZ0lTbv_Z3As5BfIYzaMlwUzFGvCVOq2MXVjRK81XOAZ6wIsyKOxva16zjbZryr2V_m3yZ4twI3CPEzJch11_qnhInirHltej-tGg6ySfLaTYeAkw4xYGwENMBBhN5t9odANpScZP_xx5bNfwdW1so6FkV1WhpKlCywoxk_vYZxo187d89bbiu-xOZUa5D-ycFkd1-1rjPXLGE_g5bc4jcQBvNBc-5FDbvt4aJlTQqjpdeppxhxn_gjkPGIAacYDI7szOLC-WYajTStbksUju1iQCyli11kPx0E66me_ZVwOX07f1lRF6D2brWm1LcMAHM3bQUK0LuyVwWPxld64uSAEsvSKsRyJERc7nZUgLf7COnUrrkxgIUNjukbdT2JVN_I-3l3b4YXg6JVD7Y5g0QYBKgXEFpZrDbBVhzo7PXPAhJD6-c3DcUQyRZExbrnFV56RwWuExphw8lYnbMvxPWImiVmB9nRVgFKD0TYaw1sidPSSlZt8Uw34VZzHWIZQAQY0BMjR33fefg42XQ1YzIwPmDx4GYXLl7HNIIVbsRsibKaJnf49mz2qnLC1K272zXSPljO11Ke1MNnsnKyUH7mcwEs9nhTsnMgEOx_TyMLRYo-VEHBDLuEOiBo with request id 74dd7114-feb5-4188-bc20-b1a8eea5f26d
INFO: sub = kuksa.val
INFO: kuksa-vss = object
INFO: iss = Eclipse KUKSA Dev
INFO: iat = 1516239022
INFO: exp = 1767225599
INFO: admin = true
INFO: sub = kuksa.val
INFO: kuksa-vss = object
INFO: iss = Eclipse KUKSA Dev
INFO: iat = 1516239022
INFO: exp = 1767225599
INFO: admin = true
VERBOSE: Receive action: getMetaData
VERBOSE: VssDatabase::getMetaData: VSS specific path =$['Vehicle']
VERBOSE: Receive action: set
VERBOSE: Set request with id dc59f6e4-6622-4b34-a331-f9cbfd4b3c4f for path: Vehicle.Speed with attribute: value
INFO: Connect to MQTT server localhost:8090
VERBOSE: MQTTPublisher::Publish topic vss/Vehicle/Speed
VERBOSE: SubscriptionHandler::publishForVSSPath: set value 100.0 for path Vehicle.Speed
ERROR: read: bad method
ERROR: read: bad method
ERROR: read: bad method
ERROR: read: bad method
<infinite loop>


Is it something with the Security authentication ?  Kuksa-val-server runs on an infinite loop with "ERROR: read: bad method" displayed on trying to set the Vehicle.Speed value from Kuksa-client. Looking for your kind support.

**Comment by Vinait** [comment]
Dear Team, Will the kuksa-val-server supports certificate based authentication using server and client certificates ?

**Comment by erikbosch** [comment]
Hi!

In the long log above it seems that you use port 8090 for both websocket and mqtt (`--mqtt.port 8090`), and that does not work, they must use different ports. As you do not specify any port for `mosquitto_sub`you shall not specify anything in KUKSA.val either, so that both use default (1883). That could explain the infinite loop, KUKSA.val Server first updates on port 8090 which basically means that it sends data to itself. 

For the last comment, for websocket I suspect that we actually do not support mutual authentication, i.e. server does not ask for or check the client certificate. For MQTT authentication; I actually do not know if we support authentication at all, there have not been any active work in that area lately. I guess it is best to review the code yourself. Have a nice weekend

**Comment by Vinait** [comment]
Hi

Thank you for taking valuable time in responding to my query.
For the clarification-1( MQTT without authentication), able to figure out and works well.
Will investigate on MQTT with authentication also, Will check on Kuksa-val **databroker** repository supporting this feature ? 
Thank you.

**Comment by erikbosch** [comment]
Concerning KUKSA.val Server and MQTT - without being an expert in MQTT TLS setup it seems that the configuration options are too limited to support TLS. We have an "insecure" option at https://github.com/eclipse/kuksa.val/blob/7937c6163aa1f3ceb6c04ad1b39a569dfbd34df7/kuksa-val-server/src/MQTTPublisher.cpp#L55, but I assume we need at least the possibility to use https://mosquitto.org/api/files/mosquitto-h.html#mosquitto_tls_set to specify what root CA to use to verify server, and potentially also client certs if mutual authentication is wanted.

I do not know of any ongoing work or plans in this area. If you test it out and identify needed changes then feel free to create a Pull Request with the changes needed. To my knowledge the Databroker has as of today no MQTT support

**Comment by Vinait** [comment]
Sure, Will check on the same. Thank you !

**Comment by SebastianSchildt** [comment]
Closing this, as we are are not planning putting more efforts into the old val-server (might still consider PRs if they come up)
