### ISSUE TITLE
Docker container Kuksa DBC Feeder not Build in CI Pipieline

### ISSUE THREAD

**Issue by anntexx** [eclipse/kuksa.val#238]
While docker containers of GPSFeeder, Kuksa.val, etc. are build in the CI build pipeline automatically, there is no build target for the DBC feeder in the Jenkins file.
Can we add the DBC feeder into the jenkins file as well as to be able to download the container in the end from the pipeline?

**Comment by SebastianSchildt** [comment]
Fixed in new Feeder project https://github.com/eclipse/kuksa.val.feeders integrated in #300
