### ISSUE TITLE
Kuksa.val manual build fail on RaspberryPi 

### ISSUE THREAD

**Issue by terilenard** [eclipse/kuksa.val#250]
I am trying to manually compile the kuksa.val on a RaspberryPi 4 (4 cores with 8gb ram configuration) but it keeps failing in the same spot. The build was done on a clean make on master. I am attaching bellow the output from make. Any ideas what is causing this error? 
                                                                                                                                                                           
[97%] Built target grpc++_error_details                                                                                   
[97%] Built target grpc++_reflection                                                                                
[97%] Built target grpc++_alts                                                                                                                           
[98%] Built target grpcpp_channelz                                                                                                              
[98%] Building CXX object src/CMakeFiles/kuksa-val-server-object.dir/AccessChecker.cpp.o                                                                 [98%] Building CXX object src/CMakeFiles/kuksa-val-server-object.dir/Authenticator.cpp.o                                                                 [99%] Building CXX object src/CMakeFiles/kuksa-val-server-object.dir/BasicLogger.cpp.o                                                                  [99%] Building CXX object src/CMakeFiles/kuksa-val-server-object.dir/GrpcConnection.cpp.o  
cc1plus: error: -Werror=deprecated-copy: no option -Wdeprecated-copy                                                                                      compilation terminated due to -Wfatal-errors.                                                                                                             
make[2]: *** [src/CMakeFiles/kuksa-val-server-object.dir/build.make:79: src/CMakeFiles/kuksa-val-server-object.dir/AccessChecker.cpp.o] Error 1           
make[2]: *** Waiting for unfinished jobs....                                                                                                              
cc1plus: error: -Werror=deprecated-copy: no option -Wdeprecated-copy                                                                                      compilation terminated due to -Wfatal-errors.                                                                                                             
make[2]: *** [src/CMakeFiles/kuksa-val-server-object.dir/build.make:92: src/CMakeFiles/kuksa-val-server-object.dir/Authenticator.cpp.o] Error 1          
 cc1plus: error: -Werror=deprecated-copy: no option -Wdeprecated-copy                                                                                      compilation terminated due to -Wfatal-errors.                                                                                                             
make[2]: *** [src/CMakeFiles/kuksa-val-server-object.dir/build.make:105: src/CMakeFiles/kuksa-val-server-object.dir/BasicLogger.cpp.o] Error 1            
cc1plus: error: -Werror=deprecated-copy: no option -Wdeprecated-copy                                                                                      compilation terminated due to -Wfatal-errors.                                                                                                            
 make[2]: *** [src/CMakeFiles/kuksa-val-server-object.dir/build.make:118: src/CMakeFiles/kuksa-val-server-object.dir/GrpcConnection.cpp.o] Error 1         
make[1]: *** [CMakeFiles/Makefile2:5444: src/CMakeFiles/kuksa-val-server-object.dir/all] Error 2                                                          make: *** [Makefile:163: all] Error 2

**Comment by SebastianSchildt** [comment]
Hmm it looks like to compiler is too old (or new), which operating system are you using on the Pi? Ubuntu? Raspberry OS? Can you you send the output of  `cat /etc/issue` and maybe compiler versions (`gcc ––version`, `g++ --version`

It will be a few days before I have a Pi to test.

@wenwenchenbosch any other ideas, or hint where to remove the -Werror=deprecated-copy option for testing?

**Comment by terilenard** [comment]
> Hmm it looks like to compiler is too old (or new), which operating system are you using on the Pi? Ubuntu? Raspberry OS? Can you you send the output of `cat /etc/issue` and maybe compiler versions (`gcc ––version`, `g++ --version`
> 
> It will be a few days before I have a Pi to test.
> 
> @wenwenchenbosch any other ideas, or hint where to remove the -Werror=deprecated-copy option for testing?

I am using the latest  version of rasbian, now named Raspberry Pi OS (https://www.raspberrypi.com/software/).

cat /etc/issue
`
Raspbian GNU/Linux 10 \n \l  
`

uname output:
` 
Linux raspberrypi 5.10.63-v7l+ #1496 SMP Wed Dec 1 15:58:56 GMT 2021 armv7l GNU/Linux 
`

gcc --version:
`
gcc (Raspbian 8.3.0-6+rpi1) 8.3.0 
`

g++ --version
`
g++ (Raspbian 8.3.0-6+rpi1) 8.3.0    
`

**Comment by terilenard** [comment]
I have update the distro from buster to bullseye. 

cat /etc/issue : `Raspbian GNU/Linux 11 \n \l `
uname output: `Linux raspberrypi 5.10.63-v7l+ #1496 SMP Wed Dec 1 15:58:56 GMT 2021 armv7l GNU/Linux `

I have recompiled kuksa.val on clean, with:
gcc: `gcc (Raspbian 10.2.1-6+rpi1) 10.2.1 20210110  ` 
g++: `g++ (Raspbian 10.2.1-6+rpi1) 10.2.1 20210110 `

Now I am getting the following compilation error:
[make_output.log](https://github.com/eclipse/kuksa.val/files/8114690/make_output.log)

I will also test with the lastest version of Rasbian and update the issue.

**Comment by terilenard** [comment]
I found the same error here: https://github.com/protocolbuffers/protobuf/issues/8508

**Comment by SebastianSchildt** [comment]
Ah good find! Maybe we need to look into updating our grpc dependency

**Comment by SebastianSchildt** [comment]
Hi @terilenard  can you check whether this PR https://github.com/eclipse/kuksa.val/pull/251 solves your problem (starting in a fresh folder, or deleting build folder, to be sure your manual patch isn't there)

If you do not want to checkout the fork, here is a quick link to a zip with sources:
https://github.com/boschresearch/kuksa.val/archive/refs/heads/upgrade_grpc_dependecy.zip

**Comment by terilenard** [comment]
Hi @SebastianSchildt . I have cloned the _upgrade_grpc_dependecy_  branch from boschresearch. Please find below the output of the clean build together with the gcc/g++ version and OS version.

```
[ 98%] Linking C executable example64
[ 98%] Built target example64
Scanning dependencies of target minigzip64
[ 98%] Building C object _deps/grpc-build/third_party/zlib/CMakeFiles/minigzip64.dir/test/minigzip.o
[ 98%] Linking C executable minigzip64
[ 98%] Built target minigzip64
[ 99%] Generating ../proto/kuksa.pb.cc, ../proto/kuksa.pb.h, ../proto/kuksa.grpc.pb.cc, ../proto/kuksa.grpc.pb.h, ../proto/kuksa_mock.grpc.pb.h
Scanning dependencies of target kuksa-val-server-object
[ 99%] Building CXX object src/CMakeFiles/kuksa-val-server-object.dir/AccessChecker.cpp.o
In file included from /home/pi/kuksa_fork/kuksa.val/src/../include/AccessChecker.hpp:17,
from /home/pi/kuksa_fork/kuksa.val/src/AccessChecker.cpp:15:
/home/pi/kuksa_fork/kuksa.val/src/../include/interface/IAccessChecker.hpp:18:10: fatal error: jsoncons/json.hpp: No such file or directory
18 | #include <jsoncons/json.hpp>
     ^~~~~~~~~~~~~~~~~~~
     compilation terminated.
make[2]: *** [src/CMakeFiles/kuksa-val-server-object.dir/build.make:98: src/CMakeFiles/kuksa-val-server-object.dir/AccessChecker.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:6073: src/CMakeFiles/kuksa-val-server-object.dir/all] Error 2 
make: *** [Makefile:182: all] Error 2 
pi@raspberrypi:~/kuksa_fork/kuksa.val/build $ git branch                                                                                               
master                                                                                                                                                  
* upgrade_grpc_dependecy 

pi@raspberrypi:~ $ gcc --version                                                                                                                          
gcc (Debian 10.2.1-6) 10.2.1 20210110 

pi@raspberrypi:~ $ g++ --version                                                                                                                          
g++ (Debian 10.2.1-6) 10.2.1 20210110 

pi@raspberrypi:~ $ uname -a                                                                                                                               
Linux raspberrypi 5.10.92-v8+ #1514 SMP PREEMPT Mon Jan 17 17:39:38 GMT 2022 aarch64 GNU/Linux 
```

**Comment by SebastianSchildt** [comment]
Ahh, the submodules are not checked out,
If you clone from git use `git clone —recursive`

If you already checked out or used the zip, in the working directory do

`git submodule update —init`

**Comment by terilenard** [comment]
Hi @SebastianSchildt . Sorry for the late response. I have re-build kuksa after updating the submodules. Works as expected on a clean checkout. I haven't modified anything regarding the compiler versions mentioned above, nor the system version.

The changes on the this branch seems to fix the problem.

Thank you very much!

**Comment by SebastianSchildt** [comment]
Thanks for testing! 👍
