### ISSUE TITLE
Getting targetValue on something not an actor gives unclear error message

### ISSUE THREAD

**Issue by SebastianSchildt** [eclipse/kuksa.val#275]
When trying to get targetValue on something other than an actor, the message might be misleading

```json
Test Client> getValue Vehicle/Speed targetValue
{
    "action": "set", 
    "error": {
        "message": "Can not get Vehicle/Speed with attribute targetValue.", 
        "number": "403", 
        "reason": "Forbidden"
    }, 
    "requestId": "e074b5bd-6354-4a9d-8f81-483dadf4979d", 
    "ts": "2022-05-23T21:05:24.1653339924Z"
}
```

It looks like an access problem, even if full rw rights on Vehicle/Speed are available. We should check whether at least the "message" path can be made more clear (preferably without too much "special case" coding)

**Comment by lukasmittag** [comment]
That's an old bug can we close this @SebastianSchildt ?

**Comment by lukasmittag** [comment]
Yes, there is another issue opened which describes it as it is now -> #490 if there is not TargetValue the client gives this: 
```
getTargetValue Vehicle.Powertrain.Transmission.TravelledDistance
{
    "path": "Vehicle.Powertrain.Transmission.TravelledDistance"
}
```

**Comment by SebastianSchildt** [comment]
Would keep both open, one issue is, that you even can set target values on unsuitable signals, the other seems to be that instead of giving an unclear error message now you get none upon retrieving. So fore tracking purposes let's keep both open. Hopefully both can be fixed in one go

**Comment by lukasmittag** [comment]
Set is fixed but get seems to have the same behavior. Keeping open.
