### ISSUE TITLE
target_values in databroker

### ISSUE THREAD

**Issue by SebastianSchildt** [eclipse/kuksa.val#326]
For actuators databroker needs to make a difference between current values (as might be provided by feeders) and target values (i.e. a desired state by the application)

API-wise this will be part of #308 , but it needs to be implemented databroker-wise

It should be possible to unambiguously set current and target values, so that a subscriber might watcht the current value, or instead listen to target values (so it can interact on someip/can to actually do something)

Extend existing integration tests for a basic check of this feature

**Comment by AkhilTThomas** [comment]
According to the VSS specifications
``sensor [optional]
The sensing appliance used to produce the data entry.

actuator [optional]
The actuating appliance consuming the data entry``

The actuator is always a consumer of data hence a data point defined in vss as of type actuator will only read the data and never change it. Whereas the sensor type will write it.

So is there a need for target and value? From an app point of view  the Seat position value is always the target set by the app i.e. Cabin.Seat.Position is only updated by the app

Please correct me if my understanding about the sensor and actuator are wrong.

**Comment by SebastianSchildt** [comment]
I think this is from here https://covesa.github.io/vehicle_signal_specification/rule_set/data_entry/sensor_actuator/ , and seems to describe optional fields to annotate where a data is orginated or consumed. @erikbosch  do you know? Like annotating target ECUs or something? have those ever been used?

There is a bit of history, VSS always had the concept of "actors" and "sensors". On the data model side "you don't care", you just "mark" things as sensor and actuators. However, in VSS it is common practice (except a few exceptions), to not model "set points" separately from from current values.

Now in VISS (the suggested  W3C protocol to access VSS data read/write it), in V1 they never formally gave it any thought/documented how to to do it. So what for example we in KUKSA did, was using VISS to "set" sensor values from a feeder and let apps "read/subscribe" them, Works perfectly for telemetry use cases. Problem was, as VSS does not make a distinction on the data model level, except labeling. So what is the meaning of "writing" an actuator in V(i)SS?.

Actually the VISS creators had the idea "writing" an actuator always writes target, reading gives current value (see also https://raw.githack.com/w3c/automotive/gh-pages/spec/VISSv2_Core.html#read ), however with it comes the consequence that to get current values into your VSS database, you would need a different API (from VISS view "don't care), to get data into your VSS server.

That never made sense for us in the in-vehicle use case of kuksa.val, where we want to have one interface to deal with VSS .

So in the seat example, for the "App" you are right
 - your app will write seat positon actuators (and expect this to be target values)   (SET target)
 - your app might want to read seat positions (and would expect this to be current values, e.g. showing/tracking whether a seat reached position)   (READ CURRENT)

Now look under kuksa.val, lets call it seat service/feeder
 - it will probbably subscibe the actor (i.e. expects to receive the target values), and does some low level magic to affect the change (READ TARGET)
 - it will want to feedback the current positon of a seat to kuksa.val, so higher levels now that (SET CURRENT)

In kuksa.val we support all this in one API, as such you need to specify what to read/write.
Also it is not always that clear cut in the example, what is a "feeder/service" below kuksa.val and what is an "app", see the "signal refinement" example here https://github.com/eclipse/kuksa.val/blob/master/doc/system-architecture.md

**Comment by erikbosch** [comment]
The text on sensor/actuator fields in https://covesa.github.io/vehicle_signal_specification/rule_set/data_entry/sensor_actuator/ is further discussed in https://github.com/COVESA/vehicle_signal_specification/issues/302. They have as far as I know never been used.

**Comment by SebastianSchildt** [comment]
Closing this as actuators are supported in kuksa.val.v1 API in databroker meanwhile
