### ISSUE TITLE
Cargo edition/version requirements for databroker

### ISSUE THREAD

**Issue by erikbosch** [eclipse/kuksa.val#328]
In the databroker cargo file edition 2018 is stated as requirement, but when I tried to build it complained. Reason seems to be the dependency to clap v 3.1.10 (using 2018) that by my cargo was replaced by the newer v3.2.16 which use edition 2021.

My understanding (with limited cargo/rust knowledge) is that we:

- Either need to change the `Cargo.toml` file so that cargo does not try to load newer versions with edition 2021 requirements
- Or we mention edition 2021 as a build requirement (and possibly change 2018 to 2021 in the `Cargo.toml`

https://github.com/eclipse/kuksa.val/blob/master/kuksa_databroker/databroker/Cargo.toml

**Comment by SebastianSchildt** [comment]
@argerus any suggestions, what is "best". is 2021 Rust "too new", or is it the new normal?

**Comment by SebastianSchildt** [comment]
"works for me"/CI, but question remains: Did we "solve" this, is it "fixed by accident".

Currently the Cargo still refers to 2018 and it seems to work.

@argerus  @erikbosch  do we have an issue here, or can this be closed?

**Comment by AlexanderLanin** [comment]
Regardless of the original issue, it's definitely time to switch to 2021. It's just one year till the next version ;-)
