### ISSUE TITLE
Python Lib wheel build in actions

### ISSUE THREAD

**Issue by SebastianSchildt** [eclipse/kuksa.val#362]
In additions to the client docker, we should also just build the wheel (for installation via pip) and provide it as build artifact, so we can test it along the way also outside the context of the container

Command for building the wheel (see current dockerfile)
```
python3 setup.py bdist_wheel
```

**Comment by SebastianSchildt** [comment]
@romainletendart This is an older issue, do you think it (still) makes sense?
Idea here was: We do need to have a script to build wheels anyway (before uploading to Pypi), so it might be useful to also run it via CI and archive it (not as a "release artifact", but more during PRs and stuff, so you can grab it from GH actions for easy testing)

**Comment by romainletendart** [comment]
¯\_(ツ)_/¯

**Comment by SebastianSchildt** [comment]
I think doing a local pipenv from checked out git is easy enough, for releaes will habe pypi anyway
