### ISSUE TITLE
Improve documentation of Go client.

### ISSUE THREAD

**Issue by erikbosch** [eclipse/kuksa.val#369]
In top level [README](https://github.com/eclipse/kuksa.val/blob/master/README.md) we describe it as a library, but in [kuksa_go_client README](https://github.com/eclipse/kuksa.val/blob/master/kuksa_go_client/README.md) we only state how to start the client. We do not describe how to build/use the library. We also do not describe what the client does.

I assumed it was a command line client like kuksa_viss_client but it is rather just an example client that tries to do some things and then exits.

I suggest that we improve the documentation to make it clearer that  [main.go](https://github.com/eclipse/kuksa.val/blob/master/kuksa_go_client/main.go) is an example client that can be used as designbase. Possibly also add some guidelines on how to integrate the library into your client. As it does not seem that we actually publish/release the kuksa-go-library, I assume the integration approach is to manually copy the files in https://github.com/eclipse/kuksa.val/tree/master/kuksa_go_client/kuksa_viss to your own project, or to use kuksa.val repo as a submodule or similar.

**Comment by SebastianSchildt** [comment]
Fixed (well improved) in #451 
We can reopen more specific issues as they arise
