### ISSUE TITLE
DBCFeeder cannot handle 7 byte entries

### ISSUE THREAD

**Issue by bs-jokri** [eclipse/kuksa.val#374]
The file candump.log contains 7 and 8 byte entries. The 7 byte entries are not properly processed. It gives the error

```
ValueError: Short data.
2022-10-07 13:19:33,901 WARNING dbcreader: Error Decoding: ID:614
```

A possible fix could be in line 89 of dbc2val/dbcreader.py
```
decode = self.db.decode_message(msg.arbitration_id, msg.data, allow_truncated=True)
```

**Comment by erikbosch** [comment]
I have a PR to remove the short lines in https://github.com/eclipse/kuksa.val.feeders/pull/23.

But this brings up an interesting discussion. Do we know if the "short lines" are correct or why they are short? I.e. that they contain correct values if one just would append 0x00 as the last byte? I.e. that the tool that created the log just omit the last byte(s) if they are 0x00? If so, it may be correct to accept truncated lines. But looking at the log it does not seem that trailing zeros by default are omitted.

If we look at `266#` it seems that all 8 byte entries end with `0x01`. I assume that `allow_truncated` means that we would consider the 7 byte lines and just use `0x00` for the last byte. But for the signal using that 8th byte that would mean that it would get a faulty value, doesn't it? If so better to ignore those lines and give a warning as today if found.


```
(1597243012.936965) elmcan 266#1D00112F110087
(1597243012.939446) elmcan 257#A444605452010000
(1597243012.946638) elmcan 266#1C00112F11008701
```

**Comment by SebastianSchildt** [comment]
We meanwhile cleaned the example CAN log of those entries (they were captured incorrectly, so technically speaking dbc feeder was correct complaining)
