### ISSUE TITLE
Consistent naming convention

### ISSUE THREAD

**Issue by lukasmittag** [eclipse/kuksa.val#376]
Define a consistent naming convention for the packages of kuksa.val e.g. kuksa-feeders kuksa_databroker kuksa-val-server.

Everything camel case or everything separated by dash

**Comment by erikbosch** [comment]
We have a proposal at https://github.com/eclipse/kuksa.val/wiki/KUKSA-Naming-Guidelines
Guess that is sufficient, or what do you think @lukasmittag ?

**Comment by lukasmittag** [comment]
Yes, its documented well now. What I meant by this is also the underscores and dashes. I think we there should also agree on one way forward. So using only dashes or underscores in all names and not having one name dashed and one name underscored.

**Comment by erikbosch** [comment]
Yes there should definitively be a pattern, and when we move to new repos is a good time to enforce it. I know that for instance pyoi do not like/accept underscore, but can we use dash/minus everywhere?, or is it so that we need to use both underscore and dash/minus, but specify preferred alternative for cases where both can be used.

**Comment by lukasmittag** [comment]
I can not think of cases were dashes wouldn't work. But for example for the structure of kuksa client directory it was necessary. I guees it would have been dumb to name both folders kuksa-client and so there is one kuksa_client directory with a kuksa-client folder in it.

**Comment by lukasmittag** [comment]
since we're moving to a new organization. This is discussed an will be finished soon.

**Comment by erikbosch** [comment]
We are about to archive this repo soon. If you consider this issue as important please file a new issue at one of the new Kuksa repos at https://github.com/eclipse-kuksa
