### ISSUE TITLE
Document config dictionary for kuksa_(viss)_client

### ISSUE THREAD

**Issue by SebastianSchildt** [eclipse/kuksa.val#377]
When using the python lib, you can configure tokens, ip, port etc. by supplying a dictionary when intiializing the library. I think this is not clearly documented. 

See also #371 

We should improve the documentation there

**Comment by erikbosch** [comment]
We are about to archive this repo soon. If you consider this issue as important please file a new issue at one of the new Kuksa repos at https://github.com/eclipse-kuksa
