### ISSUE TITLE
Check/enable Support for array types

### ISSUE THREAD

**Issue by SebastianSchildt** [eclipse/kuksa.val#40]
Need to extend val to deal with array types, that have been introduced to VSS here https://github.com/GENIVI/vehicle_signal_specification/pull/159

A first PR including an array pint for testing is https://github.com/GENIVI/vehicle_signal_specification/pull/177

Also open questions: Does VSS-tools `getValue` need to get more intelligent for this?

**Comment by wenwenchenbosch** [comment]
add read for support datatype
