### ISSUE TITLE
databroker: Inconsistent behaviour on empty lists for Set() vs Get(), Subscribe()

### ISSUE THREAD

**Issue by romainletendart** [eclipse/kuksa.val#405]
Invoking `Set()` with an empty list of `updates` doesn't raise any gRPC errors.
Invoking `Get()` with an empty list of `entries` raise:
```python
	status = StatusCode.INVALID_ARGUMENT
	details = "No datapoints requested"
```
Invoking `Subscribe()` with an empty list of `entries` raise:
```python
	status = StatusCode.INVALID_ARGUMENT
	details = "Subscription request must contain at least one entry."
```

**Comment by erikbosch** [comment]
We are about to archive this repo soon. If you consider this issue as important please file a new issue at one of the new Kuksa repos at https://github.com/eclipse-kuksa
