### ISSUE TITLE
Do not have "magic" default tokens in Python library 

### ISSUE THREAD

**Issue by SebastianSchildt** [eclipse/kuksa.val#406]
See also discussion in #402 and #371

The python library sometimes tries to guess a usable token file with lines like

```python
self.tokenfile = config.get('token', str(self.default_cert_path / 'jwt/all-read-write.json.token'))
```

That is an uglyiness we inherited from the previous version of the client. This is wrong, because it is unexpected behaviour.

It is different from shipping default certs/and tokens for testing, that is fine, because it should be transparent when and where they are used, e.g. if we modify our clients that in their _configuration_ file it refers to a default token, that is fine, I just think we should not have code "deep in the lib" that goes like "hmm, no token given, let's use some secret path instead then"

@romainletendart i guess up to you cleaning the lib - or having opinions wrt to this

**Comment by erikbosch** [comment]
This applies to `*.pem` / `*.key` files used for TLS-communication as well, like in the example below, or? I.e. we shall not make any assumption on where they are stored or what they are called?

https://github.com/eclipse/kuksa.val/blob/master/kuksa-client/kuksa_client/cli_backend/__init__.py#L31

```
        self.default_cert_path = pathlib.Path(kuksa_certificates.__path__[0])
        self.cacertificate = config.get('cacertificate', str(self.default_cert_path / 'CA.pem'))
        self.certificate = config.get('certificate', str(self.default_cert_path / 'Client.pem'))
        self.keyfile = config.get('key', str(self.default_cert_path / 'Client.key'))
```

**Comment by SebastianSchildt** [comment]
Not sure  is exactly the same, or depends on usage. Assuming there is a "default path" for certs,  I think it might be ok 
 - for the CLI client (not necessarily the lib) to load default certificates unless otherwise instructed
 - for the library part it might still be ok to load certificates for checking TLS server cert from a default location, if not overiden (could be discussed, but for practical purposes I think there will not be many installations where the endpoint is really signed by an "official" system CA). But might want to print a waring "Using builtin default CA" or something like that 

A little like when your browser/app communicates with facebook or tesla, etc.: Of course things required for the TLS part can be checked without any additional config, but of course  there will be no JWT to post crap or unlock your car, until provided by the user/requested via AP before

So I think the JSON token as mentioned above is the critical thing to get out here, but we should take a good look at the other things as well and think clearly what is needed as default here and how it can be made obvious to the user..

In the example I am not sure what applies to which i.e. is Client.key even used at all currently?


I think the line here is: It would still be good if downloading a release, you can still just fire up a server/Broker and client and be connected (without defaulting either  to --insecure or needing to set up a PKI first) but without too many hard coded assumptions that will be unexpected down the road.  Maybe it is hard, like putting this  🟥 into that  🔴

**Comment by romainletendart** [comment]
I don't really understand why having a default location for the token file is uglier than having a default location for all `*.pem` and `*.key` files. All those files should only be used when testing things manually i.e. through interactive CLI.

Whenever one wants to start using kuksa-client not through its CLI but through its API, I think we shouldn't have any default locations for all those files. At least, default values for those settings shouldn't end up in kuksa-client's python code.

Everything that relates to security should have sane default values. Currently, anyone running `pip install kuksa-client` will have the same Client.key file being used (even though that one isn't really used in practice).

Also, kuksa-client dict-based configuration is not very user-friendly currently and every kuksa-client user needs to implement its own config.ini logic.

So I think if we want to fix something here, we could add configuration file logic to kuksa-client and provide a test.ini file with default locations.

**Comment by SebastianSchildt** [comment]
> I don't really understand why having a default location for the token uglier than having a default location for all *.pem and *.key files.

I think what is uglier here is, that it loads a file with very specific authorisation (all-read-write), which means with default certs, if you play with access rights, but something went wrong (i.e. the you mistyped something in the not-really-documented config dict, the client lib would go like "Ooh, can't see a token here, let me fix that for you with this super handy powerful token", which in a test setup might make debugging harder. In a "real" setup (i.e. where the server is instructed to use another key to verify jwt tokens), it will not even be useful at all
 

> Whenever one wants to start using kuksa-client not through its CLI but through its API, I think we shouldn't have any default locations for all those files. At least, default values for those settings shouldn't end up in kuksa-client's python code.
That is probably true.

> Also, kuksa-client dict-based configuration is not very user-friendly currently and every kuksa-client user needs to implement its own config.ini logic. So I think if we want to fix something here, we could add configuration file logic to kuksa-client and provide a test.ini file with default locations.

Yes, that seems reasonable. And I think we are not that far with the config dict (because that is actually what the current clients get from there ini files, and just passing the relevant section, i.e. https://github.com/eclipse/kuksa.val.feeders/blob/cb00dbf647aa8ebaa53e7f063aadf005b7ad34e2/gps2val/gpsd_feeder.py#L47). I think it mainly misses documentation, and maybe beeing a little bit verbose in logs about what is found and what not, and maybe waring about unknown keywords.
And maybe less magic defaults, i.e. instead of things like
```
self.serverIP = config.get('ip', "127.0.0.1")
```
rather something where it says "Error: Hey, you did not tell me where to connect to. I am out!"
(side note: "ip" is bad here, actually it should be host or server or something because DNS names work as well,


> And I would remove the kuksa_certificates python package and installation completely. I don't think test certificates, keys and tokens should be shipped as part of kuksa-client's python package.

I agree. Might still be part of the client docker for testing, but probably should not be "pip installed" for everyone.

**Comment by erikbosch** [comment]
We are about to archive this repo soon. If you consider this issue as important please file a new issue at one of the new Kuksa repos at https://github.com/eclipse-kuksa
