### ISSUE TITLE
databroker: Check for allowed_values

### ISSUE THREAD

**Issue by romainletendart** [eclipse/kuksa.val#408]
At the time of writing, databroker does not check if a new field's value belongs to field's `Metadata.allowed_values`.
This means `Set()` gRPCs will always succeed as long as the data type matches even though the new value shouldn't be valid.

**Comment by lukasmittag** [comment]
Do we set the field for allowed values by default?

**Comment by lukasmittag** [comment]
also not existing in sdv proto or am I wrong so no back compatibility

**Comment by argerus** [comment]
> Do we set the field for allowed values by default?

No, but there is support for parsing it from the VSS json file provided at startup.

> also not existing in sdv proto or am I wrong so no back compatibility

I don't see why it wouldn't be backwards compatible... If there's no `allowed` present, _all_ values (of the correct type) are allowed, right.

**Comment by SebastianSchildt** [comment]
My understanding what needs to be done here is:

 - making sure, if "allowed_values" exists for any VSS signal described in the jSON, that databroker reads/stores that information (maybe already done/happening?)
 - When a datapoint is set, check if the datatype is correct (should already happen, although #496  ?) and then,  _if_ there is some allowed_value restriction for that signal, only set it, if the value is valid (i.e. one of allowed values) and return an error otherwise (this is definitely not happening currently)

**Comment by sophokles73** [comment]
The DataBroker struct indeed correctly verifies the type of a datapoint to be set. It is just that the corresponding UpdateError is not converted to the gRPC proto definition's DataEntryError when the response to a request is being sent.

**Comment by lukasmittag** [comment]
ActiveAutonomyLevel": {"allowed": ["SAE_0", "SAE_1", "SAE_2_DISENGAGING", "SAE_2", "SAE_3_DISENGAGING", "SAE_3", "SAE_4_DISENGAGING", "SAE_4", "SAE_5"], "comment": "Follows https://www.sae.org/news/2019/01/sae-updates-j3016-automated-driving-graphic taxonomy. For SAE levels 3 and 4 the system is required to alert the driver before it will disengage. Level 4 systems are required to reach a safe state even if a driver does not take over. Only level 5 systems are required to not rely on a driver at all. While level 2 systems require the driver to be monitoring the system at all times, many level 2 systems, often termed \"level 2.5\" systems, do warn the driver shortly before reaching their operational limits, therefore we also support the DISENGAGING state for SAE_2.", "datatype": "string", "description": "Indicates the currently active level of autonomy according to SAE J3016 taxonomy.", "type": "sensor", "uuid": "b101c6928fc55948b1cc485e568ecd8d"}

This allowed is meant by allowed_values? @SebastianSchildt

**Comment by SebastianSchildt** [comment]
Done in #502
