### ISSUE TITLE
Deadlock caused by exceptions 

### ISSUE THREAD

**Issue by wenwenchenbosch** [eclipse/kuksa.val#41]
Changing of databases are protected by mutex, see https://github.com/boschresearch/kuksa.val/blob/a696d9f0dac1faf84ab8da18a7dd8a932345a352/src/VssDatabase.cpp#L616

But jsoncons raises exceptions if sth. goes wrong. All exceptions are cached, but mutex is not released after sending `JsonResponses::malFormedRequest` response. Then, the vss server will go to a deadlock when a second request comes.

**Comment by SebastianSchildt** [comment]
Is there any easy/generic way to make this more robust?

**Comment by SebastianSchildt** [comment]
Will close for now, until it bites us again :)
