### ISSUE TITLE
Reintroduce autocompletion in Python command line client for GRPC

### ISSUE THREAD

**Issue by SebastianSchildt** [eclipse/kuksa.val#411]
kuksa_(viss)_client used to support tab-automcompletion for VSS Paths in the VISS (websocket) side. This does not work in GRPC side.

For usability reasons (as the cmdline client really is about exploring/debugging) we should add this feature for GRPC connections.

It can probably not be a direct port of the VISS side, because that makes use of the KUKSA VISS getMetadata call (which basically gives you verbatim excerpts from the VSS json tree)

**Comment by romainletendart** [comment]
I don't know how this should work with the unified API.
Since the switch to that new API, here is what the client gets back from databroker when querying a wildcard:
```console
Test Client> getMetaData *
{
    "error": {
        "code": 404,
        "reason": "not_found",
        "message": "Path '*' not found"
    },
    "errors": [
        {
            "path": "*",
            "error": {
                "code": 404,
                "reason": "not_found",
                "message": "Path '*' not found"
            }
        }
    ]
}
```
I think wildcards are only supported with the query syntax of the former databroker API.
@argerus any thoughts?

**Comment by SebastianSchildt** [comment]
Do we have a specific way to query the childs of a node? Like a Metadata Field we can query?

**Comment by lukasmittag** [comment]
One option could be to use the newest vss release json file. Would then not be backwards compatible though.

**Comment by SebastianSchildt** [comment]
I think the only "good way" is, when this is done via API, e.g. requesting the children of any Node.

I do however not think that also adding the (functionlity-wise overlapping) sdv API is the solutions, and I think kuksa.val.v1 can not yet do it, it would at least need something liuke StringArray children in Metadata. Which is only one but  may or may not be the best way to do it

**Comment by lukasmittag** [comment]
Is there a reason why not handling it like in sdv API?

**Comment by argerus** [comment]
I think it would make sense to add a `List( "wildcard pattern", [fields] )` to the `kuksa.val.v1` API that would return all matching VSS entries. The syntax of "wildcard pattern" should be the same as what the authorization scope uses.

**Comment by SebastianSchildt** [comment]
That makes sense to me, but thinking of authorization, would it returns everything where you possess a read scope? Would you "see" the existence of a Child if you have no access?

And what would we expect this to return. An array of all metadata?

**Comment by rafaeling** [comment]
Here is the draft PR for autocompletion: https://github.com/eclipse/kuksa.val/pull/605

**Comment by SebastianSchildt** [comment]
Done in #653
