### ISSUE TITLE
Move DB "SQL" queries over to new interface

### ISSUE THREAD

**Issue by SebastianSchildt** [eclipse/kuksa.val#414]
Databroker supports "free form" SQL queries. Those are not yet part of the kuksa.val.v1 API. Before retiring any interfaces we need to add that capability.

(Working theory: Might just be an RPC taking a string as query, but the answers might be strucutred similar to subscribe events currently)

**Comment by erikbosch** [comment]
We are about to archive this repo soon. If you consider this issue as important please file a new issue at one of the new Kuksa repos at https://github.com/eclipse-kuksa
