### ISSUE TITLE
Complex datatypes/structs in KUKSA.val

### ISSUE THREAD

**Issue by SebastianSchildt** [eclipse/kuksa.val#422]
We should have an idea if/how we would support "struct" support currently being discussed in VSS.

See https://github.com/COVESA/vehicle_signal_specification/pull/511 and the linked issues there for a lot of discussion.

Currently the specific "syntax"/capabilites model-wise are discussed (so still time to bring input), once that is clarified, the question is if/how to support this in databroker.

Capability-wise this might also be something of a middle ground between "plain VSS" as of now and "VSC

It will likely not be adopted by the _standard_ catalogue immediately, but once/if that happens we should either already be able to use it, or have decided why we will not support it.

**Comment by lukasmittag** [comment]
@erikbosch as far as I understood/read is the discussion closed without agreeing on something? Do we want this even if COVESA not agrees on it?

**Comment by erikbosch** [comment]
The referenced PR was only for discussion, the actual implementation have been handled by other PRs. Current status is:

- How to define structs in VSS syntax are described in https://covesa.github.io/vehicle_signal_specification/rule_set/data_entry/data_types_struct/
- How to add type files to tools is defined at https://github.com/COVESA/vss-tools/blob/master/docs/vspec2x.md#handling-of-data-types

Current status is that the "core" exporters support structs, but not other exporters like binary, graphql, franca and so on. By that reason COVESA VSS-project might be a bit reluctant to yet add signals using types/structs to VSS standard catalog.

I do not see any urgent need to support structs in kuksa.val, but defining the syntax of how to give/get values could be done already now.

**Comment by sanyakamra** [comment]
Hello @erikbosch and @SebastianSchildt ,
I'm interested in incorporating the struct datatype into my project within the Kuksa ecosystem. Could you please guide me in the right direction regarding whether struct is supported in the Kuksa Broker? I've been able to generate a JSON file from vSpec (v4.1), but every time I attempt to volume the updated JSON into the broker container (v0.4.1), I encounter a _Error: ParseError_

**Comment by erikbosch** [comment]
I added an issue to give better warning/error in the new repo: https://github.com/eclipse-kuksa/kuksa-databroker/issues/14 Struct is currently not supported in Databroker.

I guess it is not that straightforward to support. A possible solution could be to invent some generic struct/array-type in the Proto-files, but then some additional work would be need on both client and server side to handle that generic type, like agreeing in which order data should be included in the generic struct

**Comment by SebastianSchildt** [comment]
What Erik said. The challenge with struct is, we would not "teach" databroker an e.g. proto defintion of a specific struct, because we want the compiled databroekr version to be independent of the VSS model you might load in the future.

But it would be probably possible to add an "opaque" struct datatype that just transfers (from perspective of databroker) a bunch of bytes. As Erik said, then Sender/publisher and subscriber would need to agree how to parse it, databroker would just deliver the bytes

**Comment by erikbosch** [comment]
We are about to archive this repo soon. If you consider this issue as important please file a new issue at one of the new Kuksa repos at https://github.com/eclipse-kuksa
