### ISSUE TITLE
Setting multiple paths in cmdline client

### ISSUE THREAD

**Issue by SebastianSchildt** [eclipse/kuksa.val#424]
We can set multiple target values using the Python CLI as of https://github.com/eclipse/kuksa.val/pull/418 

We might want to extend this to normal values as well, and think about whether this can be rolled into a single command  (currently there is e.g. subscribe and subscribeMultiple

**Comment by romainletendart** [comment]
As kuksa-val-server, our only VISS/ws server, does not seem to support getting/setting/subscribing to multiples paths in one go, we need to keep the non-multiple commands/APIs around.

**Comment by SebastianSchildt** [comment]
We might want  to "emulate" that behavior with setting them in a loop on VISS side, or giving an error if more than one value is set. But for now since #429  was merged  at least we have it consistentl, so lets close this
