### ISSUE TITLE
Databroker container not listening to interrupt signals

### ISSUE THREAD

**Issue by mikehaller** [eclipse/kuksa.val#433]
The databroker container (master as of 2022-12-09) does not seem to correctly handle system interrupt signals, such as SIGTERM, SIGINT.

Observed behavior:
- When shutting down the container runtime or stopping the container, the databroker container keeps running until the container runtime does a timeout and forcefully kills the container.
- Esp. for shutdown of the system, it is observable that eg systemd is waiting long time for Kanto-CM to shut down, as it waits for the databroker container to exit.

Expected behavior:
- databroker container listens for signals (SIGINT and SIGTERM) and gracefully shuts down (eg closing open channels)

How to test:
- Create a container with kuksa.val databroker: `docker run ghcr.io/eclipse/kuksa.val/databroker:master`
- Stop it with `docker stop --time 60 <container>`
- It should stop much faster than the 60 seconds

Notes:
There is a timeout setting for container runtime. So if a container is not properly handling signals, it will forcefully kill the process at some time. This is system dependent configuration and only meant as a fallback. Containers should behave nicely to also ensure a quick shutdown.

**Comment by SebastianSchildt** [comment]
Thanks for reporting this

I pulled current version
```
% docker pull ghcr.io/eclipse/kuksa.val/databroker:master
master: Pulling from eclipse/kuksa.val/databroker
b473b36a3d93: Pull complete 
3101a6ca42fc: Pull complete 
0365c865b14e: Pull complete 
a277386aafd3: Pull complete 
Digest: sha256:67f2799b9ddc9bc83902c44734fd10823aa716c2b087898d0b0c7bf3ec08ab06
Status: Downloaded newer image for ghcr.io/eclipse/kuksa.val/databroker:master
ghcr.io/eclipse/kuksa.val/databroker:master
```

Starting like 

```
 % docker run -it --rm --net=host ghcr.io/eclipse/kuksa.val/databroker:master 
```

and then using 

```
docker stop 8be3a7683daf
```

blocks a few seconds, and then seems to force quit db with no further messages.

Interestingly, doing the same thing as above, but using Ctrl-C works:

```
% docker run -it --rm --net=host ghcr.io/eclipse/kuksa.val/databroker:master 
2022-12-09T18:34:41.215170Z  INFO databroker: Init logging from RUST_LOG (environment variable not found)
2022-12-09T18:34:41.215246Z  INFO databroker: Starting Kuksa Data Broker 
2022-12-09T18:34:41.215380Z  INFO databroker: Populating metadata... from file 'vss_release_3.0.json'
2022-12-09T18:34:41.217510Z  INFO databroker: Listening on 0.0.0.0:55555
2022-12-09T18:34:41.217534Z  INFO databroker::broker: Starting housekeeping task
^C2022-12-09T18:34:42.437679Z  INFO databroker: received SIGINT
2022-12-09T18:34:42.437834Z  INFO databroker::grpc::server: Shutting down
```

Maybe we catch SIGINT but not SIGTERM? Need to look into it.

Also pinging @argerus

**Comment by argerus** [comment]
> Maybe we catch SIGINT but not SIGTERM? Need to look into it.

Hmm, databroker was initiating shutdown on SIGINT and SIGHUP.

The intention was probably to do it on SIGINT and **SIGTERM**...
