### ISSUE TITLE
Update JSONCons

### ISSUE THREAD

**Issue by SebastianSchildt** [eclipse/kuksa.val#44]
We use jsonscons to deal with... JSON

We use a pretty old version (0.105.0) and should update it.

We already had an update for 0.130.0 with CQ20506 here https://github.com/eclipse/kuksa.apps/pull/24 

Current version is  0.156.0  https://github.com/danielaparker/jsoncons/releases

@rohoet  How hard is it to clear a new version? As it is just bugfixe with same license, would you be able to merge such a change and CQ later? If not is there alreay a newer version for piggy back? If not can you make a CQ for 0.156.0? (should have written this in pseudocode 😄  ) 

@wenwenchenbosch  Any opinion whether we should switch to submodule (or repo tool), instead of mirroring here, in case we update?

**Comment by rohoet** [comment]
Using the already cleared jsoncons 0.130.0 is fine.
I'll file a new CQ for jsoncons 0.156.0. 
Until the new CQ is cleared, we must not submit a new release, but merging into master is also fine.
