### ISSUE TITLE
Error after testclient quit

### ISSUE THREAD

**Issue by wenwenchenbosch** [eclipse/kuksa.val#47]
After using testclient connect the kuksa client like this:
```
> python -m pipenv run python testclient.py
VSS Client> connect 
Websocket connected!!
VSS Client> quit
```

Kuksa client report the following errors:
```
> ./kuksa-val-server
kuksa.val server
Commit 517fad4-dirty from 2020-09-03T09:09:49+02:00
Update vss path to /home/wenwen/tools/kuksa.val/build/src/vss_rel_2.0.json
Update cert-path to /home/wenwen/tools/kuksa.val/build/src/.
Log START
VERBOSE: Try reading JWT pub key from /home/wenwen/tools/kuksa.val/build/src/./jwt.key.pub
VERBOSE: SubscribeThread: Started Subscription Thread!
VERBOSE: VssDatabase::VssDatabase : VSS tree initialized using JSON file = /home/wenwen/tools/kuksa.val/build/src/vss_rel_2.0.json
INFO: Initializing Boost.Beast web-socket and http server on port 8090
INFO: Starting Boost.Beast web-socket and http server
VERBOSE: Receive action: getMetadata
INFO: VssCommandProcessor::processQuery: Unknown action getMetadata
ERROR: read: stream truncated
ERROR: JSON parse error
```

**Comment by wenwenchenbosch** [comment]
I created an issue in websockets repo to ask why https://github.com/aaugustin/websockets/issues/893

**Comment by wenwenchenbosch** [comment]
@nayakned I tested with node red, no similar issues there. `disconnect` function works well with node red websocket.

**Comment by nayakned** [comment]
So as it turns out, the Kuksa Python Client awaits on the incorrect close() for websocket.
https://github.com/boschresearch/kuksa.val/blob/master/kuksa_viss_client/__init__.py#L219

websocket.close() only initiates the closing of the websocket and not its completion. 
Awaiting on wait_closed() solves the issue. PR coming up shortly.

**Comment by nayakned** [comment]
Similar case also on the golang client. Current close() function just closes the underlying TCP connection.
https://pkg.go.dev/github.com/gorilla/websocket#Conn.Close

**Comment by nayakned** [comment]
Problem still exists for SSL sockets. Maybe related to this:
https://stackoverflow.com/questions/32046034/what-is-the-proper-way-to-securely-disconnect-an-asio-ssl-socket/32054476#32054476

**Comment by SebastianSchildt** [comment]
Only affects websocket and is no real issue, just "optics", closing.
