### ISSUE TITLE
Registration of datapoints in Databroker

### ISSUE THREAD

**Issue by erikbosch** [eclipse/kuksa.val#485]
As of today it is not possible (using the kuksa.val.v1 gRPC interface) to register new data points in Databroker. The updateMetaData/set_metadata only works for signals that already exists. It is a possible extension to the API (and databroker) to allow registration of new signals.

```
Test Client> updateMetaData Vehicle.Speed {"max":9999}    
OK
Test Client> updateMetaData Vehicle.Speed2 {"max":9999}
{
    "error": {},
    "errors": [
        {
            "path": "Vehicle.Speed2",
            "error": {
                "code": 404,
                "reason": "not_found",
                "message": "Vehicle.Speed2 not found"
            }
        }
    ]
}
Test Client>
```

**Comment by SebastianSchildt** [comment]
duplicate #543

**Comment by erikbosch** [comment]
We are about to archive this repo soon. If you consider this issue as important please file a new issue at one of the new Kuksa repos at https://github.com/eclipse-kuksa
