### ISSUE TITLE
Automatic check of licenses in source files

### ISSUE THREAD

**Issue by erikbosch** [eclipse/kuksa.val#486]
To avoid that we end up with source code files without proper license text it would be great if our CI could make at least some basic checks, like finding all files with a certain suffix (*.rs, *.py, ...) and do a grep to check that it contains an SPDX line.

**Comment by SebastianSchildt** [comment]
Just dropping some things I came accross
https://github.com/openMSL/sl-1-0-sensor-model-repository-template/blob/main/.github/workflows/spdx.yml


https://github.com/Persival-GmbH/spdx
https://github.com/enarx/spdx

**Comment by lukasmittag** [comment]
This should be supported in feeders and services repo too. I guess.
