### ISSUE TITLE
Move to authorization by default, option to disable

### ISSUE THREAD

**Issue by SebastianSchildt** [eclipse/kuksa.val#487]
Preserving part of the discussion in #475 . Currently we are adding auhtorization features but not enabling them by default. A way to go, to handle this graceful in the future might be the introduction of a configuration parameter, where we change  the default over time:

One sort-of future proof way might be to include a commandline parameter that describes the access to unauthorized clients, something like

```
--unauthorized_access [ALL,NONE,READ_ONLY,<custom_token>
```

and we could start with `ALL` as default, then sometime later print a warning, that it will change to `NONE` in a later version.

I think this is a useful feature even, when the default and recommended way is using auhtorization. There might deployments, where a certain set of data should be available to anyone, and also for testing it might come in handy.

The steps timewise could be

 1. Add authorization. It is optional and a warning is printed informing the user that authorization will be required (by default) in the future.
 2. Add flag to allow unauthorized access (i.e. like the example). The warning (above) is removed when this flag is used. Users can start using this flag if they intend to continue allowing unauthorized access (when it becomes required by default).
 3. Make authorization required by default.

**Comment by erikbosch** [comment]
We are about to archive this repo soon. If you consider this issue as important please file a new issue at one of the new Kuksa repos at https://github.com/eclipse-kuksa
