### ISSUE TITLE
Concept for signal update frequency

### ISSUE THREAD

**Issue by erikbosch** [eclipse/kuksa.val#488]
The concept for controlling how often signal value updates shall be sent to clients is not well defined and not well documented. We have some pieces here and there:

* In [DBC Feeder](https://github.com/eclipse/kuksa.val.feeders/blob/main/dbc2val/mapping.md) there is a possibility to control how often signals are sent to Databroker
* Databroker has some built-in support for selecting ChangeType, but it is typically not controllable by either API or config

... and we lack an overall concept documentation giving recommendations for deployments ("How to keep clients happy while minimizing CPU usage and data transfer)

**Comment by SebastianSchildt** [comment]
Maybe related #560

**Comment by SebastianSchildt** [comment]
I think cleint side this is worked on here as well https://github.com/eclipse/kuksa.val/pull/734

anyway, as this is the "old" repo shall we close here @erikbosch ?

**Comment by erikbosch** [comment]
There are things going on here and there - see also https://github.com/eclipse-kuksa/kuksa-python-sdk/pull/21.

What we possibly need to discuss is where to put/describe the concept from an end to end perspective, including also providers like can/dbc provider. The pull requests so far are very much based on code snippets, and doe not really give any good documentation/recommendations. But where should we put that? That is also true for some other documentation in https://github.com/eclipse/kuksa.val/tree/master/doc. Do we possibly aim to use kuksa-website for hosting general KUKSA documentation?

**Comment by erikbosch** [comment]
We are about to archive this repo soon. If you consider this issue as important please file a new issue at one of the new Kuksa repos at https://github.com/eclipse-kuksa
