### ISSUE TITLE
Authorisation documentation improvements/extensions

### ISSUE THREAD

**Issue by SebastianSchildt** [eclipse/kuksa.val#491]
There might be some improvements we might want to do to the concept described in #471 

 - Might want to move the "potential future extensions" into a separate document/issue and just link them
 - Might want to add a more "quickstart"/howto kind of doc as an addon/alternative, that just shows how to create tokens based on one or two examples, how to sign them,  and load them in databroker, but leaving out all the OAuth/JWT background
 - We might want to specifiy a "default" audience, although that may be "application side/implementation specific" whereas databroker assumes a default audience when no other configuration is given (and thus may rather be a topic for databroker docs)

**Comment by erikbosch** [comment]
We are about to archive this repo soon. If you consider this issue as important please file a new issue at one of the new Kuksa repos at https://github.com/eclipse-kuksa
