### ISSUE TITLE
Updating current value using wrong type

### ISSUE THREAD

**Issue by sophokles73** [eclipse/kuksa.val#496]
Given that I have registered a Data Entry of, say, type uint16.
Am I right in assuming that the Databroker should reject a gRPC request to set the current value to a boolean value?

**Comment by argerus** [comment]
Yes

**Comment by sophokles73** [comment]
In my current tests this doesn't seem to be the case, i.e. the Databroker does not return any errors in its response.
This seems to be due to the fact that the gRPC server does not transform the internal *UpdateError*s to *DataEntryError*s. The [corresponding code](https://github.com/eclipse/kuksa.val/blob/751f1d62aa0263d420639760bc84a5218d82ff73/kuksa_databroker/databroker/src/grpc/kuksa_val_v1/val.rs#L146) is currently uncommented (and would not work anyway).

I can provide a PR with the missing transformation code.

**Comment by sophokles73** [comment]
@argerus what is the policy regarding the Cargo.lock file? Do you want me to include it in the PR?

**Comment by argerus** [comment]
> In my current tests this doesn't seem to be the case, i.e. the Databroker does not return any errors in its response.
This seems to be due to the fact that the gRPC server does not transform the internal UpdateErrors to DataEntryErrors. The [corresponding code](https://github.com/eclipse/kuksa.val/blob/751f1d62aa0263d420639760bc84a5218d82ff73/kuksa_databroker/databroker/src/grpc/kuksa_val_v1/val.rs#L146) is currently uncommented (and would not work anyway).
>
> I can provide a PR with the missing transformation code.

Nice.

> @argerus what is the policy regarding the Cargo.lock file? Do you want me to include it in the PR?

Unless you changed anything in the Cargo.toml, no.

**Comment by sophokles73** [comment]
I didn't change anything but if I run `cargo update` in the `kuksa_databroker` folder, then the Cargo.lock file changes *a lot* ...

**Comment by argerus** [comment]
Well, that's exactly what `cargo update` does, i.e. it updates the Cargo.lock file. We do that periodically to keep the dependencies up to date, but prefer to do it in separate PR:s.

But the Cargo.lock can (will) also change when adding new dependencies.
