### ISSUE TITLE
Builder for EntryUpdate in databroker

### ISSUE THREAD

**Issue by lukasmittag** [eclipse/kuksa.val#515]
There are some attributes of EntryUpdate (actuator_target, allowed) that could be None as value and None as in 'I don't want to set this'. For this it could be good to have some kind of builder, so that you do not mess up :)

**Comment by erikbosch** [comment]
We are about to archive this repo soon. If you consider this issue as important please file a new issue at one of the new Kuksa repos at https://github.com/eclipse-kuksa
