### ISSUE TITLE
No autocompletion in kuksa client when interacting with databroker

### ISSUE THREAD

**Issue by lukasmittag** [eclipse/kuksa.val#520]
Maybe one way of doing this could be having a look at how databroker-cli does it. Maybe even using the same mechanism trough importing rust bindings in kuksa_client project. Look here: https://github.com/PyO3/maturin

**Comment by argerus** [comment]
I don't see the point of importing a Rust crate for use in python to achieve this functionality. Autocompletion works in databroker-cli because it's using the `sdv.databroker.v1` API.

To enable it in kuksa client, we should just add the same functionality to the `kuksa.val.v1` API, see #411.

**Comment by lukasmittag** [comment]
Did not find this issue so closing it again :) Duplicate
