### ISSUE TITLE
Kuksa-client method checkConnection does not work as I expect it

### ISSUE THREAD

**Issue by erikbosch** [eclipse/kuksa.val#523]
**_Note - this issue concerns the "old" threaded kuksa-client API. That API may be considered deprecated and then improving that API may have low priority!_**

We have a [method](https://github.com/eclipse/kuksa.val/blob/master/kuksa-client/kuksa_client/__init__.py#L47) `checkConnection`

```
def checkConnection(self):
        return self.backend.checkConnection()
```

It is implemented for both ws (KUKSA.val Server) and grpc (KUKSA.val Databroker), but it is not documented how it is supposed to behave.

What I expect:

If I call it it will tell me if there is a connection to server/broker just now

How it seems to work:

It tells if there were a connection to server/broker when the client was started. I.e. it is not updated later if the server is shutdown or is started.

What I see is needed:

- Document how it is supposed to work - shall it only reflect status at start or shall it actively monitor the status
- If it shall monitor the status - make sure that it does it.

**Comment by lukasmittag** [comment]
I think it is difficult to monitor the connection. What could be possible to call ```GetServerInfo``` for grpc backend. This will give you if the connection is alive. For websocket backend I do not know if possible/ if we want to invest time into this.

**Comment by erikbosch** [comment]
If we look at actual implementation it mostly seem to be set to true when the matching handler (ws/grpc) has been initiated or is active so we could possibly rename it accordingly. But anyway not a prioritized taks
