### ISSUE TITLE
Document expected return values for kuksa-client methods, and possibly align them

### ISSUE THREAD

**Issue by erikbosch** [eclipse/kuksa.val#524]
**_Note - this issue concerns the "old" threaded kuksa-client API. That API may be considered deprecated and then improving that API may have low priority!_**

As of today it is not documented what return values to expected when using kuksa-client APIs, like in the [example](https://github.com/eclipse/kuksa.val/blob/master/kuksa-client/kuksa_client/__init__.py#L70) below.

```
    # Set value to a given path
    def setValue(self, path, value, attribute="value", timeout=5):
        return self.backend.setValue(path, value, attribute, timeout)
```

The actual response varies a lot depending on which "backend" you use, making it difficult to implement correct handling in the feeder/provider using the client, some examples of return values

Successful (ws):
```

{
  "action": "set",
  "requestId": "528137c6-92dd-4dba-b5c7-0fc403e5b683",
  "ts": "2023-03-30T12:01:33.1680174093Z"
}
```

Server down (ws):

```
{
  "action": "set",
  "path": "Vehicle.Powertrain.Transmission.CurrentGear",
  "attribute": "value",
  "value": "0",
  "requestId": "85d5d056-6b75-4ed6-aa0a-ea313f4f8896",
  "error": "timeout"
}
```

Successful(grpc)

`OK`

 Server down (grpc):

```
{
    "error": {
        "code": 14,
        "reason": "unavailable",
        "message": "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:55555: Failed to connect to remote host: Connection refused"
    },
    "errors": []
}

```

Here parsing of the result would be simplified if we always used the same return format, like always returning JSON, and always have a field error in the json on failure. I.e. instead of `OK` return `{"result":"ok"}`or similar.

**Comment by SebastianSchildt** [comment]
We should not invest too much time "unifying" it in the API, as likely eventually the val-server will be dprectated (and then we need to discuss what do to with the threaded API anyway)

What we should do, document a little better, what the "pitfalls" are,  what is to be expected here https://github.com/eclipse/kuksa.val/blob/master/kuksa-client/docs/examples/threaded.md

Maybe check if we can change `OK` to JSON form, but maybe let's not do it, if it breaks too many of our clients using this API (and we would need to upgrade everything in sync).
