### ISSUE TITLE
[Databroker] Support EC and Ed based keys

### ISSUE THREAD

**Issue by sophokles73** [eclipse/kuksa.val#533]
Currently, Databroker only supports using RSA based keys for validating JWTs as part of the authentication process.
Elliptic Curve and Edwards Curve based crypto keys are quite popular in constrained environments because the amount of data being transferred (e.g. in a TLS handshake) and the processing power required for performing cryptographic operations on them is much smaller when compared to RSA based keys.

It would therefore be beneficial, if Dataroker would support EC and Ed based keys for both, TLS handshakes as well as validating JWTs.

**Comment by erikbosch** [comment]
We are about to archive this repo soon. If you consider this issue as important please file a new issue at one of the new Kuksa repos at https://github.com/eclipse-kuksa
