### ISSUE TITLE
Getting available signals from broker

### ISSUE THREAD

**Issue by eriksven** [eclipse/kuksa.val#568]
Hi, I would like to write a program which first requests all available signals in the data broker and then reacts based on that. The general idea is then to subscribe to all available signals and write any changes to a CSV-file.

I manually managed to achieve this goal with the 'sdv.databroker.v1' interface using the databroker-cli. 
But for my solution, I am using the Python SDK from the kuksa-client through the `kuksa.val.v1` interface which seems to have a different behavior here.

## kuksa.val.v1:

Using something like 

```
client.get(entries=[EntryRequest('', View.ALL, (Field.UNSPECIFIED,))])
```
results in ' ({'code': 404, 'reason': 'not_found', 'message': 'Path not found'}, [{'error': {'code': 404, 'reason': 'not_found', 'message': 'Path not found'}}])'. Using '*' or something like 'Vehicle.*' does not work either.  

## sdv.databroker.v1:
With the databroker-cli which seems to use the sdv.databroker.v1 interface, running

```
metadata *
```
returns a list of all available signals. The proto definition for the GetMetadataRequest states: "If no names are provided, metadata for all known data points will be returned.". This is exactly what I am looking for in the other interface.

**Comment by SebastianSchildt** [comment]
Related #411

**Comment by doosuu** [comment]
The mock service currently uses both the old and the new IF just to query all metadata. Would be greatly appreciated if the kuksa.val.v1 would also support this.

**Comment by rafaeling** [comment]
Here is the draft PR for autocompletion: https://github.com/eclipse/kuksa.val/pull/605

**Comment by lukasmittag** [comment]
Done since #605 is merged
