### ISSUE TITLE
Update or Delete DevContainer

### ISSUE THREAD

**Issue by erikbosch** [eclipse/kuksa.val#569]
We have some files related to devcontainer in https://github.com/eclipse/kuksa.val/tree/master/.devcontainer
There is a little documentation in https://github.com/eclipse/kuksa.val/blob/9a4fe306036443012273f8bd622a8b05baa3706e/kuksa-val-server/README.md?plain=1#L61

We should better decide

- If we want to keep the DevContainer support
- If not, remove it
- If yes, add better documentation on how to actually use it and how it can be tested

Related to #355

**Comment by SebastianSchildt** [comment]
My personal feeling is, it shall be removed.

If none of the core team is using it in daily work, even after upgrading it will just rot again
