### ISSUE TITLE
Databroker returns success when an incorrect value type for Datapoint is established

### ISSUE THREAD

**Issue by rafaeling** [eclipse/kuksa.val#573]
I attempted to set a DataEntry, 'Vehicle.Acceleration.Lateral', by assigning the DataPoint as an int64 instead of a float. Surprisingly, the Databroker accepted the value without raising any errors, returning success. It would be beneficial if the Databroker could provide with an invalid argument error in such cases.
Subsequently, when I invoked the get function, it returned an empty DataPoint, indicating that the value had not been updated despite the previous success response.

**Comment by lukasmittag** [comment]
Please provide more information. What did you use. How does your code look like?

**Comment by lukasmittag** [comment]
https://github.com/eclipse/kuksa.val/blob/c4091636418e34bd8f93b29f015da74c5f613a23/kuksa_databroker/databroker/src/broker.rs#L373 
I think the check is here. Do not know why it gives success.

**Comment by rafaeling** [comment]
I found the reason, the enum Field variable must be initialized in the EntryUpdate request, otherwise the broker will just accept the request withouth checking whether value is valid or not.

Would it be convenient to return an error like "Please provide a valid enum Field in EntryUpdate"?

**Comment by lukasmittag** [comment]
[```
// Describes a VSS entry
// When requesting an entry, the amount of information returned can
// be controlled by specifying either a `View` or a set of `Field`s.
```](https://github.com/eclipse/kuksa.val/blob/c4091636418e34bd8f93b29f015da74c5f613a23/proto/kuksa/val/v1/types.proto#L24)
Maybe yes, but it is not necessary I guess. @argerus what's your opinion?

**Comment by argerus** [comment]
Well, firstly I think this points to a usability issue with the current design of the API.

But if we want to make it "a little bit" better, returning an error when no fields are set seems logical.

**Comment by erikbosch** [comment]
We are about to archive this repo soon. If you consider this issue as important please file a new issue at one of the new Kuksa repos at https://github.com/eclipse-kuksa
