### ISSUE TITLE
Prefferred ttl.sh image lifetime

### ISSUE THREAD

**Issue by erikbosch** [eclipse/kuksa.val#598]
As of today, in KUKSA.val and KUKSA.val.feeders we use very different settings for lifetime of the images. In some cases we do not specify and get default (24 hours), in other cases we specify 8 hours or 1 hour. Does anyone have any objection to that we use default 24 hours everywhere, which is also maximum allowed lifetime?

I sometimes feel that 8h/1h is too short, if you for instance build at end of work day and want to test next day. If no-one objects I may create PRs to do the change.

**Comment by int0x27** [comment]
I'm fine with 24h, in fact I put 8h for some images as 1h seemed too quick to expire.

**Comment by erikbosch** [comment]
Two PRs showing possible changes:

https://github.com/eclipse/kuksa.val/pull/600
https://github.com/eclipse/kuksa.val.feeders/pull/123
