### ISSUE TITLE
What is our pypi author policy?

### ISSUE THREAD

**Issue by erikbosch** [eclipse/kuksa.val#599]
As of today we list Sebastian, Naresh and Wenwen in https://github.com/eclipse/kuksa.val/blob/master/kuksa-client/setup.cfg

This also gets visible in https://pypi.org/project/kuksa-client/.

Naresh and Wenwen however are not that active in the project. From a communication perspective a public address like `kuksa-dev@eclipse.org` seems more appropriate, and that is also what we use in https://github.com/eclipse/kuksa.val/blob/master/kuksa_certificates/genCerts.sh, but then author better should be "Eclipse KUKSA project" or similar.

I can see three possible policies:

- Historical persons that never should change. That is what we have today
- Listing persons actively working with the component. if so we should possible replace Naresh and Wenwen with Erik and Lukas
- Use a "community name/e-mail", like "Eclipse KUKSA project"

For practical perspectives the second or third option seems reasonable, and the third is easiest to maintain, but require that we have a working common mail address

**Comment by lukasmittag** [comment]
I would take the third option. Easiest to maintain.
