### ISSUE TITLE
Need to revisit array handling (Quite some differences inetracting with Server vs Broker)

### ISSUE THREAD

**Issue by erikbosch** [eclipse/kuksa.val#622]
After some testing as part of v0.4.0. release preparations I have noticed a few things.

- Go Client does not support setting arrays in KUKSA Server
- The syntax supported when setting arrays in KUKSA Server and KUKSA Broker in KUKSA Python Client and KUKSA Go CLient varies a lot. For gRPC/Databroker it seems quite consistent but for Server it varies a lot. Also the way values are returned from Server/Broker or presented by client varies.

This is maybe not a problem if we will sunset KUKSA Server in the near future. But if we will keep the KUKSA Server for a longer time we need to decide how important it is that they both accept the same syntax for arguments and return data in a similar way.

**Comment by SebastianSchildt** [comment]
Let's not put any conscious efforts into val-server support core-team wise, but at least let's keep this open while server is still around (and of course accept PRs if somebody is suffcieintly annoyed by it and improves it)

**Comment by SebastianSchildt** [comment]
Closing this. Arrays haven't seen much use, so if there are any improvements/issues we should fix on databroker side. val-server is fine, and consistency here is not required
