### ISSUE TITLE
KUKSA 0.4.0 Release

### ISSUE THREAD

**Issue by erikbosch** [eclipse/kuksa.val#624]
We are preparing a 0.4.0. release of KUKSA (.val). This issue is to track progress and to handle any questions/problems reported. Our [release process](https://github.com/eclipse/kuksa.val/wiki/Release-Process) is somewhat immature and partially manual, so during the release process the visible parts on Github may be limited, and the risk exists that we need to move/remove tags, so some instability could be excepted if you use "latest version".

Current status (2023-07-28)

- KUKSA.val and KUKSA.val.feeders tagged
- Draft github releases created for both
- Docker containers marked 0.4.0 existing for all components (where we upload docker containers)
- kuksa-client 0.4.0 uploaded as PyPI package.
- Some documentation created in wiki

##Remaining Work

@SebastianSchildt to trigger approval

## References

https://github.com/eclipse/kuksa.val/releases/tag/0.4.0
https://github.com/eclipse/kuksa.val/wiki/Release-Process
https://github.com/eclipse/kuksa.val/wiki/Release-Testing
https://github.com/eclipse/kuksa.val.feeders/releases/tag/0.4.0
https://github.com/eclipse/kuksa.val.feeders/wiki/Release-Process
https://github.com/eclipse/kuksa.val.feeders/wiki/Release-Testing

**Comment by SebastianSchildt** [comment]
Done
