### ISSUE TITLE
Rename our grpc package

### ISSUE THREAD

**Issue by rafaeling** [eclipse/kuksa.val#625]
I encountered this error because there is a name conflict between our grpc package and the PyPI grpc package. Should we consider renaming it?

https://github.com/eclipse/kuksa.val/tree/master/kuksa-client/kuksa_client/grpc

**Comment by erikbosch** [comment]
So far that has not been a problem as "our" grpc is a subpackage within kuksa_client. See for example https://github.com/eclipse/kuksa.val.feeders/blob/main/dbc2val/dbcfeederlib/databrokerclientwrapper.py that import parts from both. How/When do you get an error? What error do you get?

**Comment by lukasmittag** [comment]
Yeah, this works. But if you want to import both inside the kuksa_client lib you would use grpc for both I guess. That's the problem. But @rafaeling would you mind to elaborate more where you need this?/ What your problem is?

**Comment by rafaeling** [comment]
I think we have found the solution for this problem and it can be closed. The problem came from a different reason not related to grpc conflict names.
