### ISSUE TITLE
Handling of check push rights

### ISSUE THREAD

**Issue by erikbosch** [eclipse/kuksa.val#628]
Today we have a check push right workflow in both this repo and in kuksa.val.feeders. They are however somewhat different. Preferably they should be the same and preferably we should only have one instance of the file. This can possibly be solved in the upcoming repo split by having one instance in a `kuksa-common` repo that is referenced by others (see link below on how to do it), but then we must agree on what the common rules shall be.

(Similar arguments can exist for other reusable actions and workflows)

References:
https://github.com/eclipse/kuksa.val/blob/master/.github/workflows/check_push_rights.yml
https://github.com/eclipse/kuksa.val.feeders/blob/main/.github/workflows/check_push_rights.yml
https://github.com/eclipse/kuksa.val.feeders/pull/130
https://docs.github.com/en/actions/using-workflows/reusing-workflows

**Comment by SebastianSchildt** [comment]
If it can be shared, the home shall be https://github.com/eclipse-kuksa/kuksa-actions
