### ISSUE TITLE
Invalid links for the TLS documentation pages

### ISSUE THREAD

**Issue by Chrylo** [eclipse/kuksa.val#636]
The following documents have invalid links:

- https://github.com/eclipse/kuksa.val/blob/master/kuksa_certificates/README.md
- https://github.com/eclipse/kuksa.val/blob/master/doc/tls.md

Also the example parameters for metadata don't seem to be correct anymore e.g.

`~/kuksa.val/kuksa_databroker$ cargo run --bin databroker -- --metadata ../data/vss-core/vss_release_4.0.json`
When lookin into the Dockerfile the "vss_release_4.0.json" is added to the root and not the above path.

**Comment by SebastianSchildt** [comment]
The links are fixed in #664 , can you confirm those are fine in master now @Chrylo 

I think the example metadata parameter is correct, because the command line you quoted wrks for me and is not using a container, but starts a version locally build from a working copy. Right @erikbosch ? If I misunderstand something here, please clarify @Chrylo  :)

**Comment by Chrylo** [comment]
@SebastianSchildt @erikbosch 

The links are correct now.

You are right, the command is working when not using a container. The inconsistency with the quick start guide confused me here. Because there the container is used. So when moving from there to the TLS guide and adapting it to a container it will not work. Is it a good idea to align the guides here? 

Because the following command does not work because of the above reason:
docker run -it --rm --net=host ghcr.io/eclipse/kuksa.val/databroker:master --metadata ../data/vss-core/vss_release_4.0.json
but the following does
docker run -it --rm --net=host ghcr.io/eclipse/kuksa.val/databroker:master --port 55556 --metadata vss_release_4.0.json

**Comment by SebastianSchildt** [comment]
I think "aligning" the paths in container itself is a dangerous way, as for container newbies it might not be obvious then, that of course the files need to be _in_ or mount into the container.

But the TLS page _might_ profit from "correct" commandlines when using the containers @erikbosch 

Anyway, closing this for now as the _links_ have been fixed
