### ISSUE TITLE
Python Client fails with DNS resolution which works for Databroker-CLI

### ISSUE THREAD

**Issue by eriksven** [eclipse/kuksa.val#656]
I deployed the Kuksa.val Databroker as Container App in Microsoft Azure. The URL provided by Azure is quite long with a number of subdomains and something like: `http://databroker--***.***.eastus.azurecontainerapps.io/` . Instead of the stars there are more or less random alphanumeric characters, but I do not want to post the actual address here. 

For the databroker-cli I can use the `connect` and communicate well with the databroker instance. For the Kuksa Client I get the following error:

```
kuksa_client.grpc.VSSClientError: ({'code': 14, 'reason': 'unavailable', 'message': 'DNS resolution failed for http://databroker--***.***.eastus.azurecontainerapps.io:80: C-ares status is not ARES_SUCCESS qtype=A name=http://databroker--tw614uu.gentleisland-fc8eeca4.eastus.azurecontainerapps.io:80 is_balancer=0: Domain name not found'}, [])
```

Again, I replaced the actual address with *** . Any thoughts on what the issue with the Python Client could be here?

**Comment by erikbosch** [comment]
It could possibly be related to some limitations mentioned here:

https://github.com/grpc/grpc/issues/19954
https://github.com/grpc/grpc/blob/master/doc/environment_variables.md

_"NetBIOS and DNS: If your network relies on NetBIOS name resolution or a mixture of DNS and NetBIOS name resolution (e.g. in some Windows networks) then you should use the 'native' DNS resolver or make sure all NetBIOS names are also configured in DNS. The 'ares' DNS resolver only supports DNS name resolution."_

If I remember it correctly the Python gRPC implementation use the C implementation under the hood.

So I guess it could be an idea to try to set the environment variable `GRPC_DNS_RESOLVER=native` and see if it helps. If it helps we could possibly set it as default in the container, or at least list it as a workaround. It would be great if you could try out that work-around Sven-Erik, or see if you get any other clues from the links above.

**Comment by SebastianSchildt** [comment]
So far I could not reproduce, i.e. this works for me
 - spin up internet-facing VM, connect it to a pubic IP
 - create a DNS record for that IP and using that name to connect using kuksa-client CLI

In this case VM was an ARM machine and client was running on Mac OS.

@eriksven was so kind to let me test his azure instance, where I was not able connect, with either kuksa-client or databroker CLI, although for me it seems DNS resolution worked fine and it somehow failed in a later step.

A quick glance with wireshark and databroker-cli showed that a GRPC connection is made, and a first metadata call goes TO the server, after which there is no reply, but it just looks like the Azure instance is performing an orderly shutdown (FIN, FINACK, no RST or anything) of the TCP channel. Did not investigate further, currently no Azure access, but this sees weird

**Comment by SebastianSchildt** [comment]
I have meanwhile played some more with an internet facing Kuksa (using a DNS name and Traeffik as SSL proxy) and it all worked fine.

This really seems  more like a an issue in the specific Azure setup used, and not a general problem. As long as there are no further information to replicate this, I suggest closing this @eriksven?

**Comment by eriksven** [comment]
@SebastianSchildt it is ok for me to close this issue since the evidence is high that there was more an issue with the specific setup in Azure and the Databroker itself.
