### ISSUE TITLE
RISC V support

### ISSUE THREAD

**Issue by SebastianSchildt** [eclipse/kuksa.val#666]
As this question pops up pretty regularly these days... Create this issue for tracking

Currently RISC V is not supported, the main culprit are the required RUST crypto libs for TLS and the JWT tokens that rely on the "ring" base library https://github.com/briansmith/ring

There have been issues and PRs raised for almost two years, but while the Git is sort of active the whole project seems to be semi-abandoned and has not had a release in a long time.

The most recent developments seem to be in this PR, 

https://github.com/briansmith/ring/pull/1627

so if RISC V support is crucial for you, try to move things over there.

**Comment by argerus** [comment]
Maybe this newly [announced funding](https://briansmith.org/lets-build-a-fips-rust-crypto) will result in a new release supporting more targets (including RISC-V).

> In parallel with the FIPS-related work, I will release the 0.17 version of *ring* that supports a much wider set of targets than *ring* has supported up to now.

**Comment by SebastianSchildt** [comment]
Nice, somebody found money for that guy. Lets hope 🙏  something comes out, my RISC board is getting bored without KUKSA and a second one is on the way already (https://milkv.io/duo 😄  ).

**Comment by SebastianSchildt** [comment]
Just tracking some progress: 
Meanwhile https://github.com/briansmith/ring/pull/1627 is merged, however just doing

```
[patch.crates-io]
ring = { git = 'https://github.com/briansmith/ring.git', branch='main' }
```

is not enough, as this is currently tagged version 0.17 so 0.16.20 is still being pulled from rustls and jsonwebtoken.

As a "hack" I tried clonign ring, changing Cargo.toml claiming main to be version 0.16.22  and refernecing it like

```
ring = { path = '/path/to/patched-ring' }
```

However, "unfortunately" they use their version numbers correctly, i.e. the current ring library is not compatible at least with rustls (did not dig deeper).

So it looks like
 - still waiting for an "offiical" ring 0.17.0
 - Wiating for other prjects to pick it up

**Comment by SebastianSchildt** [comment]
Apparently rustls is already work in progress: https://github.com/rustls/rustls/pull/1508

**Comment by SebastianSchildt** [comment]
So we might wanna try -aftter 0.4.1 release - upgrading some dependecnies.

Meanwhile we have the required ring  0.17 released

https://crates.io/crates/ring

And rusttls
https://crates.io/crates/rustls/0.21.8

as well as jsonwebtoken
https://crates.io/crates/jsonwebtoken/9.1.0

have versions upgraded to the new ring

**Comment by argerus** [comment]
Created a PR (#694) with updated dependencies.
`cross build --target riscv64gc-unknown-linux-gnu` doesn't fail at least...

**Comment by SebastianSchildt** [comment]
Nice. Will try on target :)

**Comment by SebastianSchildt** [comment]
With #694  should work on RISC now, keeping this open, as we are not building it by default currently. Let's see what is possible there

**Comment by SebastianSchildt** [comment]
kuksa-client docker might take a while as distroless is not supporting riscv  yet
https://github.com/GoogleContainerTools/distroless/issues/1269

However, I guess we can sit this one out, as the pypi wheel should work fine

**Comment by SebastianSchildt** [comment]
Ok let's I played with it, and would suggest post poning kuksa-client support/container a bit. It is not impossible, but it suffers the same issue we had with ARM builds for the GRPC wheels a while ago: They don't exist, so it needs to be compiled. That is more than 3 hours when doing it via QEMU. So let's sit this one out for now. If somebody has a reasonably fast RISC V target, there is no issue why a pip install should not work, but for our CI it seems too heavy currently
