### ISSUE TITLE
Unintuitive behaviour in kuksa_client

### ISSUE THREAD

**Issue by argerus** [eclipse/kuksa.val#667]
The client just returns `None` if one forgets to call connect before making a call.

```python
from kuksa_client.grpc import VSSClient, EntryRequest, View, Field

token = "eyJ0eXAiOiJKV1Qi..."

client = VSSClient(host="127.0.0.1", port=55555)
client.authorize(token=read_vehicle_speed_token)

# client.get(...) returns None
```

and fails to use the access token provided if `client.connect()` is called after `client.authorize(...)`

```python
client = VSSClient(host="127.0.0.1", port=55555)
client.authorize(token=token)
client.connect()

# client.get(...) fails with
# kuksa_client.grpc.VSSClientError: ({'code': 16, 'reason': 'unauthenticated', 'message': 'Invalid auth token'}, [])
```

**Comment by SebastianSchildt** [comment]
The first one is definitely a bug, I would expect an exception.

The second pattern stems from val-server days, when this lib was first created: In val-server "authorize" was a normal GRPC call, that leads to some state being updated in server, thus after (re)connection there was no state. We could either change this behavior vor databroker (then it is not consistent between both VSS servers, or change/rename the function so something like client.set_token(xxx) to make sure it is a property of the client object (for val-server then the databroker behavior can be emulated by firing a authorize GRPC directly after connect)

**Comment by erikbosch** [comment]
I can take a look at it. I suspect it is the two snippets below that are involved, that it more or less just do an info-output if trying to do authorize before connect. Works likely will in CLI, not so well in other use-cases. An exception seems more appropriate, but then one must make sure that it does not cause any regressions for CLI 


```

    def check_connected(func):
        def wrapper(self, *args, **kwargs):
            if self.connected:
                return func(self, *args, **kwargs)
            else:
                logger.info(
                    "Disconnected from server! Try connect.")
        return wrapper


    @check_connected
    def authorize(self, token: str, **rpc_kwargs) -> str:
        ...
        return "Authenticated"
```

**Comment by erikbosch** [comment]
A draft PR for discussion exists at #671. It changes the current behavior that only gives a hint that a connection is required to an exception. This "solves" both scenarios above, as you simply cannot call authorize if you are not connected. Did some basic testing, in an example program, but also with dbcfeeder and kuksa-client CLI to make sure there are no obvious regressions. Some more testing required though if we think this is the way to go.

For now it just gives a general exception. Or do we prefer to give VSSClientError? But if so with what parameters?

FYI: @SebastianSchildt @argerus
