### ISSUE TITLE
Insufficient read access to Vehicle.Speed

### ISSUE THREAD

**Issue by Hariprasath-TE** [eclipse/kuksa.val#670]
when i try to connect kuksa-client to node-red-dashboard its giving error.

Welcome to Kuksa Client version 0.4.0

                  `-:+o/shhhs+:`                  
                ./oo/+o/``.-:ohhs-                
              `/o+-  /o/  `..  :yho`              
              +o/    /o/  oho    ohy`             
             :o+     /o/`+hh.     sh+             
             +o:     /oo+o+`      /hy             
             +o:     /o+/oo-      +hs             
             .oo`    oho `oo-    .hh:             
              :oo.   oho  -+:   -hh/              
               .+o+-`oho     `:shy-               
                 ./o/ohy//+oyhho-                 
                    `-/+oo+/:.             

Default tokens directory: /usr/local/lib/python3.8/dist-packages/kuksa_certificates/jwt

connect to wss://127.0.0.1:8090

Test Client> getValue Vehicle.Speed
{
  "action": "get",
  "error": {
    "message": "Insufficient read access to Vehicle.Speed",
    "number": "403",
    "reason": "Forbidden"
  },
  "requestId": "f73baa4b-74f7-49ff-bdf7-8b2c41558ddd",
  "ts": "2023-09-25T05:54:05.1695621245Z"
}

ITS SHOWING THE ISSUE LIKE THIS.

**Comment by erikbosch** [comment]
KUKSA Server normally require authorization. So the first thing for you to know is how your KUKSA Server instance is configured. If it use the KUKSA example tokens (only intended for test/demo purposes) then you could use the example tokens part of the kuksa-client, you get a hint of where they are in the printout above. There are [multiple example tokens](https://github.com/eclipse/kuksa.val/tree/master/kuksa_certificates/jwt), you could possibly try something like:

`Test Client> authorize /usr/local/lib/python3.8/dist-packages/kuksa_certificates/jwt/super-admin.json.token`

**Comment by SebastianSchildt** [comment]
This is stale for some time, and it seems rather a configuration issue. Closing for now. Reopen if there seems to be an issue here
