### ISSUE TITLE
Kuksa val to cloud mqtt

### ISSUE THREAD

**Issue by kulta4** [eclipse/kuksa.val#696]
Hi,
    I am trying the same as #15  but in my case I don't have this testclient I want to connect this kuksa val to cloud through mqtt. so how to fix this case i able to do till dbcfeeder to kuksa val (databroker). what should be the next step to connect to cloud? Thank you.

**Comment by SebastianSchildt** [comment]
There is currently no "generic" component to do that, some discussion in this issue might help https://github.com/eclipse/kuksa.val/issues/684

Specifically for MQTT maybe some of the code here can be recyled https://github.com/SebastianSchildt/kuksa-tasmota-provider

It is all hardcoded to connect to a TASMOTA smart device, but it does show how to subscribe in KUKSA and then sending it to some MQTT topic

**Comment by kulta4** [comment]
> There is currently no "generic" component to do that, some discussion in this issue might help #684
> 
> Specifically for MQTT maybe some of the code here can be recyled https://github.com/SebastianSchildt/kuksa-tasmota-provider
> 
> It is all hardcoded to connect to a TASMOTA smart device, but it does show how to subscribe in KUKSA and then sending it to some MQTT topic

Thank you for the update.
I have tried this but it doesn't show any signals received there. and this repo also doesn't have discription to follow.

**Comment by kulta4** [comment]
Hi SebastianSchildt,
                 While try to run the provide with kuksa databroker I have received an Error message can please help me to implement this.



> There is currently no "generic" component to do that, some discussion in this issue might help #684
> 
> Specifically for MQTT maybe some of the code here can be recyled https://github.com/SebastianSchildt/kuksa-tasmota-provider
> 
> It is all hardcoded to connect to a TASMOTA smart device, but it does show how to subscribe in KUKSA and then sending it to some MQTT topic

Hi SebastianSchildt,
                 While try to run the provide with kuksa databroker I have received an Error message can please help me to implement this.
/content/Screenshot 2023-11-03 125543.png

**Comment by SebastianSchildt** [comment]
According to the error you likely used a string as port number? The orginal example has a number https://github.com/SebastianSchildt/kuksa-tasmota-provider/blob/08a218c943710c8f8a7d3b77ea05fd85b81f7b6d/provider.py#L26

**Comment by kulta4** [comment]
> According to the error you likely used a string as port number? The orginal example has a number https://github.com/SebastianSchildt/kuksa-tasmota-provider/blob/08a218c943710c8f8a7d3b77ea05fd85b81f7b6d/provider.py#L26

if I have this code and the kuksa databroker running in my local and I try to connect the with c2e-hono-mqtt-adaptor which I have in AWS and deploy on Kubernetes. where and how can I get the received message from hono. 

<img width="507" alt="Screenshot 2023-11-03 125543" src="https://github.com/eclipse/kuksa.val/assets/148374362/a0cc01b0-4d74-4391-8336-12c5a062146d">


with this code I changed the MQTT IP as cluster IP of my c2e-hono-mqtt-adaptor and port. in this case the code is running and I got the update from kuksa databroker but the script is not keepalive for this I add the field keepalive=60 but it doesn't work the script is disconnected within 2seconds.

**Comment by kulta4** [comment]
Hi there,
      Any update on this above case?

**Comment by SebastianSchildt** [comment]
Hi, I personally have no experience with Hono, I just used a local Mosquitto. Did you verify your MQTT Hono thingy is reachable at all, e.g. with MQTT Explorer or similar tools?

**Comment by kulta4** [comment]
Hi,
    yes, the MQTT is reachable, but it doesn't receive any signals from databroker and unable to get it from hono. Do you have any other suggestion to connect this kuksa databroker to kafka or eclipse hono or eclipse ditto?

**Comment by Hariprasath-TE** [comment]
> Hi, yes, the MQTT is reachable, but it doesn't receive any signals from databroker and unable to get it from hono. Do you have any other suggestion to connect this kuksa databroker to kafka or eclipse hono or eclipse ditto?

Hi kulta,
have you connected this kuksa databroker with eclipse hono?

**Comment by erikbosch** [comment]
We are about to archive this repo soon. If you consider this issue as important please file a new issue at one of the new Kuksa repos at https://github.com/eclipse-kuksa
