### ISSUE TITLE
[Databroker] Location of Cargo.toml

### ISSUE THREAD

**Issue by sophokles73** [eclipse/kuksa.val#697]
The `Cargo.toml` defining the workspace of the Databroker sources currently lives in the root of the repository. This seems rather odd, given that there is a dedicated `kuksa_databroker` folder which contains all code belonging to the Databroker.

FMPOV `Cargo.toml` and `Cargo.lock` (and probably `Cross.toml` as well) should better be located in `kuksa_databroker`, or am I missing something?

**Comment by sophokles73** [comment]
:+1: for moving Databroker into its own repository

**Comment by Vinait** [comment]
Dear Team
We are trying to build the Kuksa_Databroker for ARM tool chain( master branch). Getting an error, when trying to install the cross tool  using the command "cargo install cross ".  
Wondering,  Do we support Databroker  build  for  ARM platform ? Kindly support on the same please.

**Comment by erikbosch** [comment]
> Dear Team We are trying to build the Kuksa_Databroker for ARM tool chain( master branch). Getting an error, when trying to install the cross tool using the command "cargo install cross ". Wondering, Do we support Databroker build for ARM platform ? Kindly support on the same please.

This better belongs in a separate issue, but I suggest you to study how Continuous Integration build Databroker. [There](https://github.com/eclipse/kuksa.val/blob/master/.github/workflows/kuksa_databroker_build.yml#L102) you can see how binaries are built for all architectures, using `ubuntu-latest` as build environment

**Comment by erikbosch** [comment]
We are about to archive this repo soon. If you consider this issue as important please file a new issue at one of the new Kuksa repos at https://github.com/eclipse-kuksa
