### ISSUE TITLE
[Databroker] Python based integration tests

### ISSUE THREAD

**Issue by sophokles73** [eclipse/kuksa.val#698]
The integration tests in the `kuksa_databroker/integration_test` seem to provide only very limited coverage. Given that there also is a Cucumber based (integration) test suite, I wonder if it would make sense to migrate the few existing tests to Cucumber so that we do not need to maintain both test suites (including all of the boiler plate helper code around it)?

**Comment by SebastianSchildt** [comment]
Sounds good to me, if we can get same (or better) coverage. Maybe @argerus  some opinion on this, as I do think the existing integration tests were done by you?

**Comment by argerus** [comment]
I'm all for migrating them (and no, I didn't write them).

**Comment by SebastianSchildt** [comment]
Ah, that was @lukasmittag :) WHo meanwhile also tinkered with Cucumber. @lukasmittag would you agree we can get rid of the python based integration tests and achieve the same with cucumber?

**Comment by lukasmittag** [comment]
They are mostly testing the sdv.databroker.v1 interface. Cucumber and Gherkin is testing the kuksa.val.v1 interface. So I am leaning on keeping them for now. But it is possible to port them yeah (at a later time maybe). So let's keep this open.

**Comment by SebastianSchildt** [comment]
It is "still supported", especially as some user such as Velocitas are usually a lot of versions behind, but we are not modifying it and are putting new improvements/features only in the kuksa.val API. Thus,  I would not add support for sdv API in Cucumber tests. However, if the "old" tests are testing the sdv interface, it  might be worth to have still around as long as we do have the interface shipped

**Comment by sophokles73** [comment]
Fair enough. Have you already deprecated the `sdv.databroker.v1` API? If not, I predict that Velocitas will use it forever ;-)

**Comment by erikbosch** [comment]
We are about to archive this repo soon. If you consider this issue as important please file a new issue at one of the new Kuksa repos at https://github.com/eclipse-kuksa
