### ISSUE TITLE
Announcement: Migration of kuksa-client (KUKSA Python SDK)

### ISSUE THREAD

**Issue by erikbosch** [eclipse/kuksa.val#709]
We are currently working on migrating [kuksa-client](https://github.com/eclipse/kuksa.val/tree/master/kuksa-client) to a new [repository](https://github.com/eclipse-kuksa/kuksa-python-sdk). The new repository has now been created and populated, but is still in draft state. For now this means:

- Pull Requests and Issues related to kuksa-client shall still be filed to this repository
- All pull-requests/commits concerning kuksa-client merged to this repository will later be cherry-picked to the new repository
- Name of PyPI package will be kept
- Name of container will be kept, but ghcr and ttl.sh path will change. When the migration has been finished new releases will only be published to the new path, `kuksa-client:master` in this repository will no longer be updated
- When migration is finished [kuksa-client](https://github.com/eclipse/kuksa.val/tree/master/kuksa-client) source code and related work flows will after a grace period be removed from master-branch of this repository.

**Update 2023-11-17**

- A 0.4.2 pre-release exist at https://github.com/eclipse-kuksa/kuksa-python-sdk/releases
- Docker contains for 0.4.2 can be downloaded at https://github.com/eclipse-kuksa/kuksa-python-sdk/pkgs/container/kuksa-python-sdk%2Fkuksa-client
- A Pypi package 0.4.2 built from the new location exists at https://pypi.org/project/kuksa-client/0.4.2/
- A Pull Request to remove kuksa-client from this repository exists at: https://github.com/eclipse/kuksa.val/pull/710

**Recommendations**

- Test using 0.4.2 or code directly from https://github.com/eclipse-kuksa/kuksa-python-sdk and report issues, if any, either here or in the new repository.

**Comment by SebastianSchildt** [comment]
@erikbosch  I assume this can be closed as we finished this?

**Comment by erikbosch** [comment]
Finished
