### ISSUE TITLE
Can you tag the latest version?

### ISSUE THREAD

**Issue by junh-ki** [eclipse/kuksa.val#71]
Because the repo keeps being updated, I thought it would be nice to have a tag for the latest version so that the documentation I am writing won't be outdated.
Please let me know :)

**Comment by SebastianSchildt** [comment]
I do not have rights to do that here, and doing a "release" is a quite complicated process in Eclipse, but you can use the git SHAs, to refer to a specific commit, such as
https://github.com/eclipse/kuksa.val/tree/a82a1dac50eb08384f418529a734a2f9d0c8e8c4
 
(and can also git checkout a hash)

**Comment by junh-ki** [comment]
@SebastianSchildt Okay I will try that.
