### ISSUE TITLE
Issue with parquet format file while converting into json.

### ISSUE THREAD

**Issue by Hariprasath-TE** [eclipse/kuksa.val#714]
I ran s3_uploader.py file and got this kuksa_2023-Dec-01_14_47_38.928506.parquet file and then I tried to convert this file into json format by using some online converter that's giving me an error.
That error message:
Error: Invalid Input Error: No magic bytes found at end of file 'kuksa_2023-Nov-29_05_47_41.617482.parquet'
could you please suggest me to convert this file into a json format.

**Comment by erikbosch** [comment]
We are about to archive this repo soon. If you consider this issue as important please file a new issue at one of the new Kuksa repos at https://github.com/eclipse-kuksa
