### ISSUE TITLE
databroker via  c programmimg

### ISSUE THREAD

**Issue by zib0001** [eclipse/kuksa.val#718]
can we acess databroker via  c programimg

**Comment by erikbosch** [comment]
KUKSA Databroker offer two interfaces; gRPC and VISS Websocket, where gRPC is default and most mature.

[gRPC](https://grpc.io/docs/languages/) supports C++ but does not support C. In Kuksa we do not have any SDK for C++ like we have for Python but we use C++ in some example services, like the Seat Service, see for example https://github.com/eclipse/kuksa.val.services/blob/main/seat_service/src/bin/seat_service/seat_position_subscriber.cc

So if you can use C++ or any other language supported by gRPC it shall be possible to interact with databroker. If not you need to rely on the VISS Websocket interface.

**Comment by erikbosch** [comment]
Issue seems to be solved, closing it.
Please reopen if needed
