### ISSUE TITLE
Rename databroker crates/binaries

### ISSUE THREAD

**Issue by lukasmittag** [eclipse/kuksa.val#719]
See https://github.com/eclipse/kuksa.val/pull/717#issuecomment-1851852069 for a detailed discussion about the topic. 
| old |	new |	comment |
|---|---|---|
| databroker |	kuksa-databroker | | 	
| databroker-proto | 	kuksa-proto = "../kuksa-proto" | 	Local dependency, not a crate|
| databroker-cli |	kuksa-cli 	| |

**Comment by tasnuva1** [comment]
#723 (comment) is for: 
old|	new	 | comment
---|      ---|               ---|	
databroker-proto	| kuksa-proto = "../kuksa-proto" |	Local dependency, not a crate

#722 (comment) is for: 
old|	new	 | comment
---|      ---|               ---|	
databroker-cli |	kuksa-cli

Please let me know if there is a mistake or a change of plan.

**Comment by lukasmittag** [comment]
finished
