### ISSUE TITLE
node-red to any other external protocol or store as json

### ISSUE THREAD

**Issue by kulta4** [eclipse/kuksa.val#724]
Hi!
     I tried this kuksa_apps node-red demo case, in that I able to see the data which comes from kuksa-client but the changes which we have done from node-red is not replicating on databroker even I am not able to edit any signals.
    target is to achieve the cloud part. how to build this connection with our own.
    can we able to get the data as json or able to send data to mqtt externally.

**Comment by erikbosch** [comment]
We are about to archive this repo soon. If you consider this issue as important please file a new issue at one of the new Kuksa repos at https://github.com/eclipse-kuksa
