### ISSUE TITLE
[databroker-cli] SELECT query not working for kuksa.val.v1 on databroker-cli

### ISSUE THREAD

**Issue by AkhilTThomas** [eclipse/kuksa.val#725]
The SELECT query feature is not working for the databroker-cli when the protocol is set to kuksa-val-v1.

```shell
kuksa.val.v1 > subscribe SELECT Vehicle.Speed
[subscribe]  NotFound  No entries found for the provided. Path: SELECT
kuksa.val.v1 >
```
Also the autocomplete does not fill the SELECT keyword or the subsequent data points.

**Comment by SebastianSchildt** [comment]
Yes, from an API perspective we need to decide how to move forward here, currently it is in the "Old" sdv API, while the new kuksa API does not have such a feature. 

We might either decide to just bring the same call to the v1 api, or considering that this is a "different" way of interacting with databroker, (becasue if you are using the v1 API maybe you would not use SQL and vice versa) maybe split it out into a seperate API/module

I think this has not been discussed much yet.

**Comment by erikbosch** [comment]
We are about to archive this repo soon. If you consider this issue as important please file a new issue at one of the new Kuksa repos at https://github.com/eclipse-kuksa
