### ISSUE TITLE
Kuksa with QNX

### ISSUE THREAD

**Issue by vinaith** [eclipse/kuksa.val#741]
Dear Team
Good day!
Will  the Kuksa.val.server or Kuksa Databroker supports porting into QNX ? 
We tried Kuksa data broker, unable to finish because of RUST issues and Kuksa-val-server, trying it. 
Please support with your inputs.

**Comment by SebastianSchildt** [comment]
We know that KUKSA databroker can run on QNX, IF changes are made to upstream libraries. However, currently such changes seem not to be available publicly. That may or may not change, but as Eclipse KUKSA team we currently can not confirm any timeline.

So the answer - and sorry for it not being too helpful to you at this time - is: "It is possible", but you would need to do adaption to upstream libraries

**Comment by SebastianSchildt** [comment]
Just fyi, we have some things work in progress to get support upstream.,

here
https://github.com/tokio-rs/tokio/pull/6421
and here
https://github.com/tokio-rs/mio/pull/1766

there is more to b done (i.e. for crypto), but those two would already move one big blocker out of the way
