### ISSUE TITLE
[Databroker] Enabling gPRC Server Reflection

### ISSUE THREAD

**Issue by sgloutnikov** [eclipse/kuksa.val#742]
From what I have gathered gRPC Server Reflection is not enabled on the `KUKSA Databroker` and is on the `KUKSA Server`. Someone please correct me if this is not the case.

I would like to start a discussion regarding enabling it also on the Databroker, with either a toggle flag or permanently. I am also new to Rust and don't know when the tonic based gRPC reflection implementation was added, but it is [now available](https://github.com/hyperium/tonic/tree/master/tonic-reflection).

**Comment by erikbosch** [comment]
FYI @argerus

**Comment by SebastianSchildt** [comment]
As I understand it, this would come in handy for GRPC tools supporting reflection such as https://github.com/fullstorydev/grpcurl or https://github.com/IBM/gWhisper , but it assume it would also increase attack surface.

Not in the sense that somebody can figure out our 'secret' API (that is open here anyway), but but by exposing more functionality than is necessary for normal operations, so if we put support in, it seems prudent to hide it behind an optional flag?

**Comment by sgloutnikov** [comment]
Yes, agreed on the unnecessary toggle if reflection is enabled. In addition, there also shouldn't be any performance implications for enabling it. My use case for reflection is not having to distribute and compile the `.proto` files in a custom client.

**Comment by erikbosch** [comment]
We are about to archive this repo soon. If you consider this issue as important please file a new issue at one of the new Kuksa repos at https://github.com/eclipse-kuksa

For this particular issue there are some work ongoing in https://github.com/eclipse-kuksa/kuksa-databroker/pull/89
