### ISSUE TITLE
[kuksa-feeders] Support for a c(pp) SDK

### ISSUE THREAD

**Issue by nayakned** [eclipse/kuksa.val#745]
Dear Kuksa Team,

We are currently looking to integrate one of our C applications into the kuksa world.
To do this, I am looking for a C or a C++ SDK for interacting with the databroker.
kuksa-someip-provider does something like this already, but the code is tightly coupled with the someip application.

Dont you think making the databroker APIs from the kuksa-someip-provider available as a library will help integrating other C/C++ applications?

Thanks.

**Comment by AkhilTThomas** [comment]
> IMHO it would be great if we would have a `kuksa-c-sdk` or `kuksa-cpp-sdk` similar to https://github.com/eclipse-kuksa/kuksa-python-sdk. As far as I know no-one is however working on it or plan to do something in the near future. If someone one would be willing to contribute a first version we could start a discussion on where it should be stored.

I'm interested in contributing to this 😄

**Comment by erikbosch** [comment]
Discussed at Kuksa community call today. Short notes below

- We do not want to create a `kuksa-cpp-sdk` repo until we actually have something that actually can be called an SDK. We are planning to create a `kuksa-incubation` repo where this could fit mid-term, but as that repo does not yet exist initial work could be performed as a pull request to this repo.
- The [KUKSA SOME/IP provider](https://github.com/eclipse-kuksa/kuksa-someip-provider) could possibly be used as designbase, but unclear how well structured the client/SDK parts in that repo are.
- Coordination with Velocitas project could be useful, as they already have some form of CPP SDK/Client, however focusing on their needs only. Could possibly be used as designbase and extended to cover more Kuksa functionality. It anyway need to be refactored to use the "newer" databroker API.

**Comment by erikbosch** [comment]
We are about to archive this repo soon. If you consider this issue as important please file a new issue at one of the new Kuksa repos at https://github.com/eclipse-kuksa
