### ISSUE TITLE
Upgrade Jenkins build to buildx

### ISSUE THREAD

**Issue by SebastianSchildt** [eclipse/kuksa.val#75]
We should use "buildx" to build https://docs.docker.com/buildx/working-with-buildx/ instead of custom scripts Advantages

- no need to use the qemu heavy-lifting yourself: It is nice and hidden
- possibility to use native arm64 build node

However, buildx complicates docker-in-docker setup fiurther I suggest we drop it

 - main idea was to build "inside docker", so the build node has no dependencies/special setup
    - makes sense, if we have commands such as "cmake... make..." that depend on external libararies, so you are not dependant on the specific setup and versions of the node
 - the setup to use docker inside another docker is not that trivial (and means the builder can not eb that generic anyway)
 - everything we do is already in docker, so whether we do `docker build` on a docker enabled host or in a docker on a docker enabled host doesn't matter

@wenwenchenbosch opinions?
 
I tried playing with buildx setup  the #67  PR, but I will probably revert that to just provide a docker file (maybe using with out old methods), and tackle the Jenkins build renovation separately

**Comment by wenwenchenbosch** [comment]
If buildx works and fit for our usage, we should use it instead of bash script, even if buildx is still an experimental feature.

**Comment by SebastianSchildt** [comment]
Done in #79
