### ISSUE TITLE
Broker datapoints interface to retrieve metadata should include data type unit

### ISSUE THREAD

**Issue by erikbosch** [eclipse/kuksa.val#755]
This issue originates from https://github.com/eclipse/kuksa.val.services/issues/102 but moved here as it concerns Databroker

The [data unit types of VSS ](https://covesa.github.io/vehicle_signal_specification/rule_set/data_entry/data_unit_types/) should be exposed via GetMetadata as well.

Eg when subscribing to "Vehicle.Speed", the value is in "km/h" as specified. Since the spec can be overriden, it's hard for generic tools ("VSS Browser") to know the specific data type unit, unless it is exposed via the metadata interface.

**Comment by lukasmittag** [comment]
at least we have this https://github.com/eclipse/kuksa.val/pull/726 but yes would be good to have unit also shown in getMetaData call agree!

**Comment by erikbosch** [comment]
We are about to archive this repo soon. If you consider this issue as important please file a new issue at one of the new Kuksa repos at https://github.com/eclipse-kuksa
