### ISSUE TITLE
another error when building kuksa-val-server

### ISSUE THREAD

**Issue by junh-ki** [eclipse/kuksa.val#97]
I am trying to build the latest `kuksa-val-server` in my VM again. The error pops up at the end of the building process as follow:

```
[ 80%] Building CXX object src/CMakeFiles/kuksa-val-server-object.dir/MQTTClient.cpp.o
[ 80%] Built target kuksa-val-server-object
Scanning dependencies of target kuksa-val-server-core
[ 85%] Linking CXX shared library libkuksa-val-server-core.so
[ 85%] Built target kuksa-val-server-core
Scanning dependencies of target kuksa-val-server-core-static
[ 90%] Linking CXX static library libkuksa-val-server-core-static.a
[ 90%] Built target kuksa-val-server-core-static
Scanning dependencies of target kuksa-val-server
[ 95%] Building CXX object src/CMakeFiles/kuksa-val-server.dir/main.cpp.o
[100%] Linking CXX executable kuksa-val-server
CMakeFiles/kuksa-val-server.dir/main.cpp.o: In function `print_usage(char const*, boost::program_options::options_description&)':
main.cpp:(.text+0x8d): undefined reference to `boost::program_options::operator<<(std::ostream&, boost::program_options::options_description const&)'
CMakeFiles/kuksa-val-server.dir/main.cpp.o: In function `boost::program_options::validation_error::validation_error(boost::program_options::validation_error::kind_t, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)':
...
```

what am I missing here?

**Comment by SebastianSchildt** [comment]
boost program options library seems to be missing

If you have no boost installed at all, then cmake should get a version for you. If you have a suitable bosot installed, maybe it is missing program options @wenwenchenbosch  Does our cmake check for that? I would expect the error to pop up before linking during the cmake run?

**Comment by wenwenchenbosch** [comment]
@SebastianSchildt I checked it, program_options is required in our cmake.
@junh-ki Which OS is installed in your VM? Did you do a clean build? We update boost version, there may be some inconsistent there.

**Comment by junh-ki** [comment]
> boost program options library seems to be missing
> 
> If you have no boost installed at all, then cmake should get a version for you. If you have a suitable bosot installed, maybe it is missing program options @wenwenchenbosch Does our cmake check for that? I would expect the error to pop up before linking during the cmake run?

I see I think the installed boost

**Comment by junh-ki** [comment]
> @SebastianSchildt I checked it, program_options is required in our cmake.
> @junh-ki Which OS is installed in your VM? Did you do a clean build? We update boost version, there may be some inconsistent there.

@wenwenchenbosch it is ubuntu 18.04. I will update boost and try it again

**Comment by junh-ki** [comment]
I reinstalled libraries as follows:

1.

```
sudo apt-get remove libblkid-dev e2fslibs-dev libboost-all-dev libaudit-dev libssl-dev mosquitto libmosquitto-dev libglib2.0-dev
```

2.

```
sudo apt-get install libblkid-dev e2fslibs-dev libboost-all-dev libaudit-dev libssl-dev mosquitto libmosquitto-dev libglib2.0-dev
```
then removed, recreated `/build`
and 
`cmake ..`, 
`make clean`  < hopefully this is what you meant by "clean make", then
`make`

and here comes the same error:

```
[100%] Linking CXX executable kuksa-val-server
CMakeFiles/kuksa-val-server.dir/main.cpp.o: In function `print_usage(char const*, boost::program_options::options_description&)':
main.cpp:(.text+0x8d): undefined reference to `boost::program_options::operator<<(std::ostream&, boost::program_options::options_description const&)'
CMakeFiles/kuksa-val-server.dir/main.cpp.o: In function `boost::program_options::validation_error::validation_error(boost::program_options::validation_error::kind_t, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)':

```

**Comment by SebastianSchildt** [comment]
delete  the "build" FOlder and create it again. Also show the output from `cmake`

**Comment by wenwenchenbosch** [comment]
I can reproduce the error on my pc now with `cmake version 3.19.3`. I will work on it to fix the problem.
Workaround for now is, to execute `cmake` twice und will then works.

**Comment by wenwenchenbosch** [comment]
@junh-ki pls check the changes https://github.com/eclipse/kuksa.val/pull/99

**Comment by junh-ki** [comment]
@wenwenchenbosch I cloned from the latest commit of `boschresearch/kuksa.val` and the same error arised :(
```
[100%] Linking CXX executable kuksa-val-server
CMakeFiles/kuksa-val-server.dir/main.cpp.o: In function `print_usage(char const*, boost::program_options::options_description&)':
main.cpp:(.text+0x8d): undefined reference to `boost::program_options::operator<<(std::ostream&, boost::program_options::options_description const&)'

```

**Comment by junh-ki** [comment]
@wenwenchenbosch  I switched the branch to `74_update_boost` as you suggested and it's been successfully built. Thanks!

```
[ 80%] Building CXX object src/CMakeFiles/kuksa-val-server-object.dir/MQTTClient.cpp.o
[ 80%] Built target kuksa-val-server-object
Scanning dependencies of target kuksa-val-server-core
[ 85%] Linking CXX shared library libkuksa-val-server-core.so
[ 85%] Built target kuksa-val-server-core
Scanning dependencies of target kuksa-val-server-core-static
[ 90%] Linking CXX static library libkuksa-val-server-core-static.a
[ 90%] Built target kuksa-val-server-core-static
Scanning dependencies of target kuksa-val-server
[ 95%] Building CXX object src/CMakeFiles/kuksa-val-server.dir/main.cpp.o
[100%] Linking CXX executable kuksa-val-server
[100%] Built target kuksa-val-server
junh-ki@junhki-VirtualBox:~/Desktop/kuksa.val/build$ 
```
